## Drug Repositioning Database(RepoDB)
repoDB contains a standard set of drug repositioning successes and failures that can be used to fairly and reproducibly benchmark computational repositioning methods

### Download repoDB drug-diesases database
https://unmtid-shinyapps.net/shiny/repodb/

In [7]:
import pandas as pd

df = pd.read_csv("repoDB_drug_disease.csv", sep=",")
df.head()

,drug_name,drugbank_id,ind_name,ind_id,NCT,status,phase,DetailedStatus
0,ajmaline,DB01426,Ventricular arrhythmia,C0085612,NaN,Approved,NaN,NaN
1,ajmaline,DB01426,Supraventricular arrhythmia,C0428974,NaN,Approved,NaN,NaN
2,ajmaline,DB01426,Cardiac Arrhythmia,C0003811,NaN,Approved,NaN,NaN
3,emtricitabine,DB00879,HIV Infections,C0019693,NaN,Approved,NaN,NaN
4,enalapril,DB00584,Asymptomatic left ventricular systolic dysfunc...,C3698411,NaN,Approved,NaN,NaN

### Format the data files as the BioMedGPS format

In [8]:
# 只保留 Approved
df_approved = df[df["status"] == "Approved"]

In [26]:
formatted_df = pd.DataFrame()
formatted_df["source_name"] = df["drug_name"]
formatted_df["source_type"] = "Compound"
formatted_df["source_id"] = df["drugbank_id"]
formatted_df["target_name"] = df["ind_name"]
formatted_df["target_type"] = "Disease"
formatted_df["target_id"] = df["ind_id"]
formatted_df["relation_type"] = "RepoDB::therapeutic::Compound:Disease"
formatted_df["resource"] = "RepoDB"
formatted_df

,source_name,source_type,source_id,target_name,target_type,target_id,relation_type,resource
0,ajmaline,Compound,DB01426,Ventricular arrhythmia,Disease,C0085612,RepoDB::therapeutic::Compound:Disease,RepoDB
1,ajmaline,Compound,DB01426,Supraventricular arrhythmia,Disease,C0428974,RepoDB::therapeutic::Compound:Disease,RepoDB
2,ajmaline,Compound,DB01426,Cardiac Arrhythmia,Disease,C0003811,RepoDB::therapeutic::Compound:Disease,RepoDB
3,emtricitabine,Compound,DB00879,HIV Infections,Disease,C0019693,RepoDB::therapeutic::Compound:Disease,RepoDB
4,enalapril,Compound,DB00584,Asymptomatic left ventricular systolic dysfunc...,Disease,C3698411,RepoDB::therapeutic::Compound:Disease,RepoDB
...,...,...,...,...,...,...,...,...
13553,NaN,Compound,DB01075,"Dermatitis, Atopic",Disease,C0011615,RepoDB::therapeutic::Compound:Disease,RepoDB
13554,triamcinolone,Compound,DB00620,Vitiligo,Disease,C0042900,RepoDB::therapeutic::Compound:Disease,RepoDB
13555,oxytocin,Compound,DB00107,Obesity,Disease,C0028754,RepoDB::therapeutic::Compound:Disease,RepoDB
13556,melphalan,Compound,DB01042,Multiple Myeloma,Disease,C0026764,RepoDB::therapeutic::Compound:Disease,RepoDB
13557,buprenorphine,Compound,DB00921,Pain,Disease,C0030193,RepoDB::therapeutic::Compound:Disease,RepoDB

#### 对source_type and target_type进行标准化处理

In [27]:
# ---- target_id 加 UMLS: ----
t = formatted_df["target_id"].fillna("").astype(str).str.strip()
mask_t = t.ne("") & ~t.str.lower().eq("na") & ~t.str.startswith("UMLS:")
formatted_df.loc[mask_t, "target_id"] = "UMLS:" + t[mask_t]

In [28]:
# ---- source_id 加 DrugBank: ----
s = formatted_df["source_id"].fillna("").astype(str).str.strip()
mask_s = s.ne("") & ~s.str.lower().eq("na") & ~s.str.startswith("DrugBank:")
formatted_df.loc[mask_s, "source_id"] = "DrugBank:" + s[mask_s]
formatted_df

,source_name,source_type,source_id,target_name,target_type,target_id,relation_type,resource
0,ajmaline,Compound,DrugBank:DB01426,Ventricular arrhythmia,Disease,UMLS:C0085612,RepoDB::therapeutic::Compound:Disease,RepoDB
1,ajmaline,Compound,DrugBank:DB01426,Supraventricular arrhythmia,Disease,UMLS:C0428974,RepoDB::therapeutic::Compound:Disease,RepoDB
2,ajmaline,Compound,DrugBank:DB01426,Cardiac Arrhythmia,Disease,UMLS:C0003811,RepoDB::therapeutic::Compound:Disease,RepoDB
3,emtricitabine,Compound,DrugBank:DB00879,HIV Infections,Disease,UMLS:C0019693,RepoDB::therapeutic::Compound:Disease,RepoDB
4,enalapril,Compound,DrugBank:DB00584,Asymptomatic left ventricular systolic dysfunc...,Disease,UMLS:C3698411,RepoDB::therapeutic::Compound:Disease,RepoDB
...,...,...,...,...,...,...,...,...
13553,NaN,Compound,DrugBank:DB01075,"Dermatitis, Atopic",Disease,UMLS:C0011615,RepoDB::therapeutic::Compound:Disease,RepoDB
13554,triamcinolone,Compound,DrugBank:DB00620,Vitiligo,Disease,UMLS:C0042900,RepoDB::therapeutic::Compound:Disease,RepoDB
13555,oxytocin,Compound,DrugBank:DB00107,Obesity,Disease,UMLS:C0028754,RepoDB::therapeutic::Compound:Disease,RepoDB
13556,melphalan,Compound,DrugBank:DB01042,Multiple Myeloma,Disease,UMLS:C0026764,RepoDB::therapeutic::Compound:Disease,RepoDB
13557,buprenorphine,Compound,DrugBank:DB00921,Pain,Disease,UMLS:C0030193,RepoDB::therapeutic::Compound:Disease,RepoDB

In [32]:
formatted_df.to_csv("formatted_RepoDB.tsv", sep="\t", index=False)

In [29]:
import os
import os.path as osp
import subprocess


def format_RepoDB(filename):
    def get_project_root():
        try:
            return osp.dirname(osp.dirname(os.getcwd()))
        except Exception as e:
            raise RuntimeError(f"Failed to determine project root: {e}")

    try:
        root_dir = get_project_root()
        print(f"Project root directory: {root_dir}")
    except RuntimeError as e:
        print(e)
        exit(1)

    database = "customdb"
    relations_path = osp.join(
        root_dir,
        "relations",
        "repoDB",
        filename,
    )
    output_dir = osp.join(
        root_dir, "formatted_relations", "repoDB"
    )
    entities_path = osp.join(root_dir, "entities.tsv")
    log_file = osp.join(output_dir, "log.txt")
    relation_types_file = osp.join(root_dir, "relation_types.tsv")

    command = [
        "graph-builder",
        "--database",
        database,
        "-d",
        relations_path,
        "-o",
        output_dir,
        "-f",
        entities_path,
        "-n",
        "20",
        "--download",
        "--skip",
        "-l",
        log_file,
        "--debug",
        "--relation-type-dict-fpath",
        relation_types_file,
        "--allow-ignore-checking-errors", 
        "all",
    ]

    print("Executing command:", " ".join(command))

    try:
        subprocess.run(command, check=True)
    except FileNotFoundError:
        print(
            "Error: 'graph-builder' command not found. Make sure it is installed and available in the PATH."
        )
        exit(1)
    except subprocess.CalledProcessError as e:
        print(f"Error: Command execution failed with return code {e.returncode}")
        print(f"Output: {e.output}")
        exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}")
        exit(1)

In [34]:
format_RepoDB("formatted_RepoDB.tsv")

Project root directory: /Users/zhuzhixing/KG/biomedgps-data/graph_data
Executing command: graph-builder --database customdb -d /Users/zhuzhixing/KG/biomedgps-data/graph_data/relations/repoDB/formatted_RepoDB.tsv -o /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/repoDB -f /Users/zhuzhixing/KG/biomedgps-data/graph_data/entities.tsv -n 20 --download --skip -l /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/repoDB/log.txt --debug --relation-type-dict-fpath /Users/zhuzhixing/KG/biomedgps-data/graph_data/relation_types.tsv --allow-ignore-checking-errors all

2025-09-28 08:31:15 - cli:171 - INFO - Run jobs with (output_dir: /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/repoDB, db file/directory: /Users/zhuzhixing/KG/biomedgps-data/graph_data/relations/repoDB/formatted_RepoDB.tsv, databases: ('customdb',), download: True, skip: True)
2025-09-28 08:31:18 - base_parser:229 - INFO - Using allow_ignore_checking_errors=all to ignore the checking errors.
2025-09-28 08:31:18 - customdb_parser:100 - INFO - Get 13558 relations
2025-09-28 08:31:18 - base_parser:478 - INFO - Found 13558 relations.
2025-09-28 08:31:18 - base_parser:795 - INFO - Start to get entity id map.
2025-09-28 08:31:28 - base_parser:829 - INFO - The number of deduped entity type ids: 3843
2025-09-28 08:37:43 - base_parser:839 - INFO - The number of entity ids: 3843
2025-09-28 08:37:44 - base_parser:480 - INFO - Found 3843 entity ids in entity id map.
2025-09-28 08:37:44 - base_parser:494 - INFO - The number of relations before dropna: 13558
2025-09-28 08:37:44 - base_parser:496 - INFO - The number of relations after dropna: 13558
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.00%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.04%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.08%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.13%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.17%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.21%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.25%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.29%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.34%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.38%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.42%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.46%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.50%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.55%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.59%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.63%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.67%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.71%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.76%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.80%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.84%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.88%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.92%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 0.97%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.01%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.05%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.09%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.13%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.18%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.22%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.26%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.30%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.34%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.39%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.43%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.47%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.51%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.55%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.60%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.64%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.68%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.72%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.76%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.81%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.85%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.89%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.93%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 1.97%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.02%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.06%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.10%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.14%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.18%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.23%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.27%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.31%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.35%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.39%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.44%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.48%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.52%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.56%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.60%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.65%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.69%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.73%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.77%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.81%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.86%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.90%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.94%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 2.98%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.02%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.07%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.11%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.15%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.19%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.23%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.28%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.32%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.36%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.40%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.44%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.49%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.53%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.57%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.61%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.65%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.70%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.74%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.78%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.82%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.86%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.91%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.95%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 3.99%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.03%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.07%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.12%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.16%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.20%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.24%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.28%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.33%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.37%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.41%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.45%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.49%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.54%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.58%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.62%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.66%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.70%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.75%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.79%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.83%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.87%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.91%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 4.96%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.00%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.04%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.08%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.12%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.17%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.21%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.25%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.29%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.33%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.38%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.42%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.46%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.50%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.54%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.59%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.63%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.67%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.71%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.75%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.80%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.84%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.88%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.92%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 5.96%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.01%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.05%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.09%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.13%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.17%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.22%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.26%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.30%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.34%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.38%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.43%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.47%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.51%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.55%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.59%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.64%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.68%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.72%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.76%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.80%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.85%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.89%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.93%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 6.97%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.01%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.06%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.10%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.14%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.18%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.22%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.27%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.31%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.35%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.39%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.43%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.48%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.52%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.56%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.60%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.64%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.69%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.73%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.77%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.81%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.85%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.90%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.94%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 7.98%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.02%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.06%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.11%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.15%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.19%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.23%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.27%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.32%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.36%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.40%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.44%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.48%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.53%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.57%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.61%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.65%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.69%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.74%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.78%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.82%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.86%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.90%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.95%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 8.99%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.03%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.07%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.11%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.16%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.20%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.24%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.28%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.32%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.37%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.41%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.45%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.49%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.53%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.58%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.62%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.66%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.70%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.74%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.79%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.83%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.87%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.91%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 9.95%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.00%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.04%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.08%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.12%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.16%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.21%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.25%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.29%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.33%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.37%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.42%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.46%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.50%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.54%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.58%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.63%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.67%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.71%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.75%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.79%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.84%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.88%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.92%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 10.96%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.00%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.05%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.09%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.13%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.17%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.21%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.26%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.30%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.34%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.38%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.42%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.47%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.51%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.55%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.59%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.63%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.68%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.72%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.76%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.80%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.84%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.89%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.93%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 11.97%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 12.01%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 12.05%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 12.10%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 12.14%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 12.18%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 12.22%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 12.26%
2025-09-28 08:37:44 - base_parser:504 - INFO - Processing 12.31%