## Prepare a full knowledge graph dataset

We need to prepare the training, validation and external test datasets. We will use the training dataset to train the model and the test dataset to evaluate the model for all KGE models.

### [Require to Modify According to Your Situation] Prepare all relation files

We design a strategy to allow users to integrate their expected relation files for different purposes. Such as you might want to include the `malacards_mecfs` dataset when you want to train a model for ME/CFS.

In [3]:
import os

root_dir = os.path.dirname(os.getcwd())

# ---------- Parameters [Must be modified based on your situation] ----------
# dataset_name = "biomedgps-full-v20240127"
dataset_name = "biomedgps"
dataset_version = "v20250928"
skip_rows_not_in_entity_file = True
# The directory names must be consistent with the subdirectories in the formatted_relations folder.
blacklist_databases = []

# It's an optional parameter, if you don't want to split the dataset, you can ignore it.
#split_ratio = 0.8

# Which column will be kept in the final formatted file
relation_type_column = "formatted_relation_type"

# Which file will be used to format the relation types
relation_type_file = "relation_types.tsv"

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [4]:
root_dir

'/Users/zhuzhixing/KG/biomedgps-data'

In [5]:
# ---------- Load data ----------
graph_data_dir = os.path.join(root_dir, "graph_data")
formatted_relation_dir = os.path.join(graph_data_dir, "formatted_relations")

files = []
for dir in os.listdir(formatted_relation_dir):
    dir_path = os.path.join(formatted_relation_dir, dir)
    if os.path.isdir(dir_path):  # 检查是否为目录
        for file in os.listdir(dir_path):
            if file.endswith(".tsv") and file.startswith("formatted_") and dir not in blacklist_databases:
                files.append(os.path.join(dir_path, file))

print("Merging the following files:")
print("\n".join(files))

entity_file = os.path.join(graph_data_dir, "entities.tsv")
print("Number of entities: {}".format(len(open(entity_file).readlines())))

Merging the following files:
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/repoDB/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ttd/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/Fibromine/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/dgidb/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/drkg/formatted_drkg.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/biosnap_disease/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/FibROAD/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/monarch/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/cbcg/formatted_customdb.tsv
/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ctd/formatted_ctd.tsv
Number of entities: 933231

### Dependencies

In [6]:
import os
import sys

lib_dir = os.path.join(os.path.dirname(os.getcwd()), "lib")

print("Adding {} to sys.path".format(lib_dir))
sys.path.append(lib_dir)

Adding /Users/zhuzhixing/KG/biomedgps-data/lib to sys.path

In [30]:
repo_commit_id

'df0cec658dcb855f35bda63e176e9b9df7f8db79'

### Metadata for recording the steps

To save the essential information of all relation files for reproducibility.

In [8]:
from metadata import DatasetMetadata, check_repo_clean

# For getting the correct commit id, we need to check if the repo is clean. If not, you should commit your changes first.
check_repo_clean(file_suffix = ".py", raise_error=False)
repo_commit_id = os.popen("git rev-parse HEAD").read().strip()
repo_path = os.popen("git config --get remote.origin.url").read().strip()
outputdir = os.path.join(root_dir, "datasets", f"{dataset_name}-{dataset_version}-{repo_commit_id[:6]}")
os.makedirs(outputdir, exist_ok=True)

dataset_metadata = DatasetMetadata(
    repo_commit_id=repo_commit_id,
    repo_path=repo_path,
    dataset_name=dataset_name,
    dataset_version=dataset_version,
    data_files=files,
    metadata=None,
)

dataset_metadata.to_json(os.path.join(outputdir, "metadata.json"))

### Merge all relation files into one file

In [10]:
import os
import subprocess
import pandas as pd
import tempfile

temp_dir = tempfile.mkdtemp()

args = ["python3", os.path.join(lib_dir, "data.py"), "merge-files"]

for f in files:
    args.extend(["--input", f])

kg_file = os.path.join(temp_dir, "knowledge_graph.tsv")
args.extend(["--output", kg_file])

print("Running: {}".format(" ".join(args)))
args_str = " ".join(args)
!{args_str}

if os.path.exists(kg_file):
    df = pd.read_csv(kg_file, sep="\t")
    source_ids = df[["source_id", "source_type"]].drop_duplicates()
    source_ids.columns = ["id", "label"]
    target_ids = df[["target_id", "target_type"]].drop_duplicates()
    target_ids.columns = ["id", "label"]
    ids = pd.concat([source_ids, target_ids]).drop_duplicates()
    print("Number of unique entity ids: {}".format(len(ids)))
    print("Number of deduplicated relations: {}".format(len(df.drop_duplicates())))

    entities = pd.read_csv(entity_file, sep="\t")

    dataset_metadata.add_step(
        note="Merge all relation files into one file",
        entity_file_before=None,
        entity_file_after=entity_file,
        relation_file_before=None,
        relation_file_after=kg_file,
    )

Running: python3 /Users/zhuzhixing/KG/biomedgps-data/lib/data.py merge-files --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/repoDB/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ttd/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/Fibromine/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/dgidb/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/drkg/formatted_drkg.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/biosnap_disease/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/FibROAD/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/monarch/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/cbcg/formatted_customdb.tsv --input /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ctd/formatted_ctd.tsv --output /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/knowledge_graph.tsv
/Users/zhuzhixing/KG/biomedgps-data/lib/data.py:304: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(file, sep=detect_separator(file)) for file in input]
Merging the following files:  ('/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/repoDB/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ttd/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/Fibromine/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/dgidb/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/drkg/formatted_drkg.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/biosnap_disease/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/FibROAD/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/monarch/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/cbcg/formatted_customdb.tsv', '/Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ctd/formatted_ctd.tsv')
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/repoDB/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 9374
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ttd/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 14027
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/Fibromine/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 739
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/dgidb/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 1397
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/drkg/formatted_drkg.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 5464332
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/biosnap_disease/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 87130
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/FibROAD/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 1094
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/customdb/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 7597
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/monarch/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 3046730
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/cbcg/formatted_customdb.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 431
The following columns are in the /Users/zhuzhixing/KG/biomedgps-data/graph_data/formatted_relations/ctd/formatted_ctd.tsv: ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type'], Number of rows: 36160656
The following columns will be used:  ['raw_source_id', 'raw_target_id', 'raw_source_type', 'raw_target_type', 'relation_type', 'resource', 'pmids', 'key_sentence', 'source_id', 'source_type', 'target_id', 'target_type', 'formatted_relation_type']
Number of rows in the merged dataframe:  44793507

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_87811/3759005214.py:21: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(kg_file, sep="\t")

Number of unique entity ids: 200451
Number of deduplicated relations: 44793507

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_87811/3759005214.py:30: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  entities = pd.read_csv(entity_file, sep="\t")

In [11]:
kg_file

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/knowledge_graph.tsv'

### Add curation mapping step

In [21]:
import pandas as pd

# 读取全部数据
df = pd.read_csv(kg_file, sep="\t", low_memory=False)
df

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,DrugBank:DB00107,UMLS:C0000810,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB00107,Compound,MESH:D000027,Disease,BioMedGPS::Treatment::Compound:Disease
1,DrugBank:DB00917,UMLS:C0000810,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB00917,Compound,MESH:D000027,Disease,BioMedGPS::Treatment::Compound:Disease
2,DrugBank:DB01160,UMLS:C0000810,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB01160,Compound,MESH:D000027,Disease,BioMedGPS::Treatment::Compound:Disease
3,DrugBank:DB12789,UMLS:C0000810,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB12789,Compound,MESH:D000027,Disease,BioMedGPS::Treatment::Compound:Disease
4,DrugBank:DB03808,UMLS:C0000880,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB03808,Compound,MONDO:0005629,Disease,BioMedGPS::Treatment::Compound:Disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44793502,OMIM:613485,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0019171,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44793503,OMIM:613677,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013359,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44793504,OMIM:613980,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013513,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44793505,OMIM:614098,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013572,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44793506,OMIM:616973,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0014855,Disease,BioMedGPS::AssociatedWith::Pathway:Disease

In [22]:
# 读取映射表（from_id, to_id 两列）
mapping = pd.read_excel("id_redirects.xlsx") 

# 构建字典 {from_id: to_id}
id_map = dict(zip(mapping["from_id"], mapping["to_id"]))

In [23]:
# 替换前的副本
before = df[["source_id", "target_id"]].copy()

# 替换 source_id 和 target_id
df[["source_id", "target_id"]] = df[["source_id", "target_id"]].replace(id_map)

# 统计发生变化的行数
changed_rows = (before != df[["source_id", "target_id"]]).any(axis=1).sum()

print(f"共替换了 {changed_rows} 行")

共替换了 748 行

### [Optional] Filter out the relations that are not matched with our requirements

We can follow the results generated by the graph_analysis.ipynb to decide which relations should be kept.

In [28]:
kg_file_ignore_relation_types_filtered = os.path.join(
    temp_dir, "knowledge_graph_ignore_relation_types_filtered.tsv"
)

In [24]:
print("Number of relations: {}".format(len(df)))
ignore_relation_types = [
    # Virus gene relations are not useful for our use case.
    "bioarx::Coronavirus_ass_host_gene::Disease:Gene",
    "bioarx::Covid2_acc_host_gene::Disease:Gene",
    "bioarx::DrugHumGen::Compound:Gene",
    "bioarx::DrugVirGen::Compound:Gene",
    "bioarx::HumGenHumGen::Gene:Gene",
    "bioarx::VirGenHumGen::Gene:Gene",
    # We don't like associated_with relation type.
    "PrimeKG::associated_with::Disease:Gene",
    "PrimeKG::associated_with::Gene:Disease",
    "PrimeKG::associated_with::Gene:Symptom",
    "PrimeKG::associated_with::Symptom:Gene",
    # We don't like ontology tree
    "PrimeKG::parent-child::Anatomy:Anatomy",
    "PrimeKG::parent-child::BiologicalProcess:BiologicalProcess",
    "PrimeKG::parent-child::CellularComponent:CellularComponent",
    "PrimeKG::parent-child::Disease:Disease",
    "PrimeKG::parent-child::MolecularFunction:MolecularFunction",
    "PrimeKG::parent-child::Pathway:Pathway",
    "PrimeKG::parent-child::Symptom:Symptom",
]

Number of relations: 44793507

In [25]:
ignore_relation_types

['bioarx::Coronavirus_ass_host_gene::Disease:Gene',
 'bioarx::Covid2_acc_host_gene::Disease:Gene',
 'bioarx::DrugHumGen::Compound:Gene',
 'bioarx::DrugVirGen::Compound:Gene',
 'bioarx::HumGenHumGen::Gene:Gene',
 'bioarx::VirGenHumGen::Gene:Gene',
 'PrimeKG::associated_with::Disease:Gene',
 'PrimeKG::associated_with::Gene:Disease',
 'PrimeKG::associated_with::Gene:Symptom',
 'PrimeKG::associated_with::Symptom:Gene',
 'PrimeKG::parent-child::Anatomy:Anatomy',
 'PrimeKG::parent-child::BiologicalProcess:BiologicalProcess',
 'PrimeKG::parent-child::CellularComponent:CellularComponent',
 'PrimeKG::parent-child::Disease:Disease',
 'PrimeKG::parent-child::MolecularFunction:MolecularFunction',
 'PrimeKG::parent-child::Pathway:Pathway',
 'PrimeKG::parent-child::Symptom:Symptom']

In [26]:
df = df[~df["relation_type"].isin(ignore_relation_types)]
print("Number of relations after removed ignore relation_types: {}".format(len(df)))

Number of relations after removed ignore relation_types: 44793419

In [31]:
relation_type_map = pd.read_csv(
    os.path.join(graph_data_dir, "relation_types.tsv"), sep="\t"
)
relation_type_map

,relation_type,raw_description,formatted_relation_type,description,prompt_template,resource,abbr,source_type,target_type,annotation
0,PrimeKG::parent-child::Anatomy:Anatomy,Parent-child relationship between anatomies,BioMedGPS::ParentChild::Anatomy:Anatomy,A hierarchical relationship between two anatom...,Is there a hierarchical relationship between t...,PrimeKG,parent-child,Anatomy,Anatomy,NaN
1,Hetionet::AdG::Anatomy:Gene,Anatomy downregulates the gene,BioMedGPS::E-::Anatomy:Gene,The gene is not significantly expressed in a s...,Is the #Gene# not significantly expressed in t...,Hetionet,AdG,Anatomy,Gene,Anatomy–downregulates–Gene
2,Hetionet::AeG::Anatomy:Gene,Anatomy expresses the gene,BioMedGPS::E::Anatomy:Gene,The gene has a general level of expression in ...,Does the #Gene# exhibit a general level of exp...,Hetionet,AeG,Anatomy,Gene,Anatomy–expresses–Gene
3,Hetionet::AuG::Anatomy:Gene,Anatomy upregulates the gene,BioMedGPS::E+::Anatomy:Gene,The gene is significantly expressed in a speci...,Is the #Gene# significantly expressed in the #...,Hetionet,AuG,Anatomy,Gene,Anatomy–upregulates–Gene
4,PrimeKG::expression_absent::Anatomy:Gene,Anatomy lacks expression of a gene,BioMedGPS::NE::Anatomy:Gene,The gene is not expressed in a specific anatom...,"Is the #Gene# not expressed in the #Anatomy#, ...",PrimeKG,expression_absent,Anatomy,Gene,NaN
...,...,...,...,...,...,...,...,...,...,...
397,biolink::subclass_of::Phenotype:Disease,A phenotype is considered a specific manifesta...,BioMedGPS::Present::Disease:Phenotype,A symptom that is present and characteristic o...,Is the #Symptom# characteristic and present in...,biolink,subclass_of,Phenotype,Disease,NaN
398,biolink::part_of::Protein:CellularComponent,The protein is structurally part of a larger c...,BioMedGPS::InCC::Gene:CellularComponent,A gene associated with a specific cellular com...,Is the #Gene# associated with the #CellularCom...,biolink,part_of,Protein,CellularComponent,NaN
399,biolink::caused_by::Disease:CellularComponent,The disease arises due to changes in a cellula...,BioMedGPS::Causer::CellularComponent:Disease,A change or dysfunction in a cellular componen...,Does the #CellularComponent# contribute to the...,biolink,caused_by,Disease,CellularComponent,NaN
400,biolink::subclass_of::CellularComponent:Anatomy,A cellular component is viewed as a part of br...,BioMedGPS::ParentChild::CellularComponent:Anatomy,A cellular component is a part of or derived f...,Is there a hierarchical relationship between #...,biolink,subclass_of,CellularComponent,Anatomy,NaN
401,RepoDB::therapeutic::Compound:Disease,Compound has a therapeutic effect on a disease,BioMedGPS::Treatment::Compound:Disease,A compound is used in the treatment of a speci...,Is the #Compound# used in the treatment of #Di...,RepoDB,therapeutic,Compound,Disease,NaN

In [32]:
relation_types = relation_type_map["relation_type"].tolist()
relation_types

['PrimeKG::parent-child::Anatomy:Anatomy',
 'Hetionet::AdG::Anatomy:Gene',
 'Hetionet::AeG::Anatomy:Gene',
 'Hetionet::AuG::Anatomy:Gene',
 'PrimeKG::expression_absent::Anatomy:Gene',
 'PrimeKG::expression_present::Anatomy:Gene',
 'PrimeKG::parent-child::BiologicalProcess:BiologicalProcess',
 'PrimeKG::interacts_with::BiologicalProcess:Gene',
 'PrimeKG::parent-child::CellularComponent:CellularComponent',
 'PrimeKG::interacts_with::CellularComponent:Gene',
 'DRUGBANK::x-atc::Compound:Atc',
 'DRUGBANK::ddi-interactor-in::Compound:Compound',
 'Hetionet::CrC::Compound:Compound',
 'PrimeKG::synergistic_interaction::Compound:Compound',
 'DRUGBANK::treats::Compound:Disease',
 'GNBR::C::Compound:Disease',
 'GNBR::J::Compound:Disease',
 'GNBR::Mp::Compound:Disease',
 'GNBR::Pa::Compound:Disease',
 'GNBR::Pr::Compound:Disease',
 'GNBR::Sa::Compound:Disease',
 'GNBR::T::Compound:Disease',
 'Hetionet::CpD::Compound:Disease',
 'Hetionet::CtD::Compound:Disease',
 'PrimeKG::contraindication::Compound:Disease',
 'PrimeKG::indication::Compound:Disease',
 'PrimeKG::off-label_use::Compound:Disease',
 'CTD::marker/mechanism::Compound:Disease',
 'CTD::therapeutic::Compound:Disease',
 'bioarx::DrugHumGen:Compound:Gene',
 'bioarx::DrugVirGen:Compound:Gene',
 'DRUGBANK::carrier::Compound:Gene',
 'DRUGBANK::enzyme::Compound:Gene',
 'DRUGBANK::target::Compound:Gene',
 'GNBR::A+::Compound:Gene',
 'GNBR::A-::Compound:Gene',
 'GNBR::B::Compound:Gene',
 'GNBR::E+::Compound:Gene',
 'GNBR::E-::Compound:Gene',
 'GNBR::E::Compound:Gene',
 'GNBR::K::Compound:Gene',
 'GNBR::N::Compound:Gene',
 'GNBR::O::Compound:Gene',
 'GNBR::Z::Compound:Gene',
 'Hetionet::CbG::Compound:Gene',
 'Hetionet::CdG::Compound:Gene',
 'Hetionet::CuG::Compound:Gene',
 'INTACT::ASSOCIATION::Compound:Gene',
 'INTACT::DIRECT INTERACTION::Compound:Gene',
 'INTACT::PHYSICAL ASSOCIATION::Compound:Gene',
 'PrimeKG::carrier::Compound:Gene',
 'PrimeKG::enzyme::Compound:Gene',
 'PrimeKG::target::Compound:Gene',
 'PrimeKG::transporter::Compound:Gene',
 'CTD::affects^abundance::Compound:Gene',
 'CTD::affects^activity::Compound:Gene',
 'CTD::affects^binding::Compound:Gene',
 'CTD::affects^chemical synthesis::Compound:Gene',
 'CTD::affects^cotreatment::Compound:Gene',
 'CTD::affects^expression::Compound:Gene',
 'CTD::affects^localization::Compound:Gene',
 'CTD::affects^methylation::Compound:Gene',
 'CTD::affects^oxidation::Compound:Gene',
 'CTD::affects^phosphorylation::Compound:Gene',
 'CTD::affects^reaction::Compound:Gene',
 'CTD::affects^response to substance::Compound:Gene',
 'CTD::affects^secretion::Compound:Gene',
 'CTD::affects^splicing::Compound:Gene',
 'CTD::decreases^abundance::Compound:Gene',
 'CTD::decreases^activity::Compound:Gene',
 'CTD::decreases^expression::Compound:Gene',
 'CTD::decreases^methylation::Compound:Gene',
 'CTD::decreases^phosphorylation::Compound:Gene',
 'CTD::decreases^reaction::Compound:Gene',
 'CTD::decreases^response to substance::Compound:Gene',
 'CTD::decreases^secretion::Compound:Gene',
 'CTD::decreases^transport::Compound:Gene',
 'CTD::increases^abundance::Compound:Gene',
 'CTD::increases^acetylation::Compound:Gene',
 'CTD::increases^activity::Compound:Gene',
 'CTD::increases^carboxylation::Compound:Gene',
 'CTD::increases^chemical synthesis::Compound:Gene',
 'CTD::increases^cleavage::Compound:Gene',
 'CTD::increases^degradation::Compound:Gene',
 'CTD::increases^expression::Compound:Gene',
 'CTD::increases^lipidation::Compound:Gene',
 'CTD::increases^localization::Compound:Gene',
 'CTD::increases^metabolic processing::Compound:Gene',
 'CTD::increases^methylation::Compound:Gene',
 'CTD::increases^mutagenesis::Compound:Gene',
 'CTD::increases^oxidation::Compound:Gene',
 'CTD::increases^phosphorylation::Compound:Gene',
 'CTD::increases^reaction::Compound:Gene',
 'CTD::increases^reduction::Compound:Gene',
 'CTD::increases^response to substance::Compound:Gene',
 'CTD::increases^secretion::Compound:Gene',
 'CTD::increases^splicing::Compound:Gene',
 'CTD::increases^stability::Compound:Gene',
 'CTD::increases^sumoylation::Compound:Gene',
 'CTD::increases^transport::Compound:Gene',
 'CTD::increases^ubiquitination::Compound:Gene',
 'CTD::increases^uptake::Compound:Gene',
 'Hetionet::CcSE::Compound:SideEffect',
 'PrimeKG::side_effect::Compound:Symptom',
 'Hetionet::DlA::Disease:Anatomy',
 'PrimeKG::contraindication::Disease:Compound',
 'PrimeKG::indication::Disease:Compound',
 'PrimeKG::off-label_use::Disease:Compound',
 'Hetionet::DrD::Disease:Disease',
 'PrimeKG::parent-child::Disease:Disease',
 'bioarx::Coronavirus_ass_host_gene::Disease:Gene',
 'bioarx::Covid2_acc_host_gene::Disease:Gene',
 'Hetionet::DaG::Disease:Gene',
 'Hetionet::DdG::Disease:Gene',
 'Hetionet::DuG::Disease:Gene',
 'PrimeKG::associated_with::Disease:Gene',
 'Hetionet::DpS::Disease:Symptom',
 'HSDN::has_symptom::Disease:Symptom',
 'PrimeKG::phenotype_absent::Disease:Symptom',
 'PrimeKG::phenotype_present::Disease:Symptom',
 'PrimeKG::expression_absent::Gene:Anatomy',
 'PrimeKG::expression_present::Gene:Anatomy',
 'Hetionet::GpBP::Gene:BiologicalProcess',
 'PrimeKG::interacts_with::Gene:BiologicalProcess',
 'Hetionet::GpCC::Gene:CellularComponent',
 'PrimeKG::interacts_with::Gene:CellularComponent',
 'DGIDB::ACTIVATOR::Gene:Compound',
 'DGIDB::AGONIST::Gene:Compound',
 'DGIDB::ALLOSTERIC MODULATOR::Gene:Compound',
 'DGIDB::ANTAGONIST::Gene:Compound',
 'DGIDB::ANTIBODY::Gene:Compound',
 'DGIDB::BINDER::Gene:Compound',
 'DGIDB::BLOCKER::Gene:Compound',
 'DGIDB::CHANNEL BLOCKER::Gene:Compound',
 'DGIDB::INHIBITOR::Gene:Compound',
 'DGIDB::MODULATOR::Gene:Compound',
 'DGIDB::OTHER::Gene:Compound',
 'DGIDB::PARTIAL AGONIST::Gene:Compound',
 'DGIDB::POSITIVE ALLOSTERIC MODULATOR::Gene:Compound',
 'PrimeKG::carrier::Gene:Compound',
 'PrimeKG::enzyme::Gene:Compound',
 'PrimeKG::target::Gene:Compound',
 'PrimeKG::transporter::Gene:Compound',
 'GNBR::D::Gene:Disease',
 'GNBR::G::Gene:Disease',
 'GNBR::J::Gene:Disease',
 'GNBR::L::Gene:Disease',
 'GNBR::Md::Gene:Disease',
 'GNBR::Te::Gene:Disease',
 'GNBR::Ud::Gene:Disease',
 'GNBR::U::Gene:Disease',
 'GNBR::X::Gene:Disease',
 'GNBR::Y::Gene:Disease',
 'PrimeKG::associated_with::Gene:Disease',
 'CTD::marker/mechanism::Gene:Disease',
 'CTD::therapeutic::Gene:Disease',
 'bioarx::HumGenHumGen:Gene:Gene',
 'bioarx::VirGenHumGen:Gene:Gene',
 'GNBR::B::Gene:Gene',
 'GNBR::E+::Gene:Gene',
 'GNBR::E::Gene:Gene',
 'GNBR::H::Gene:Gene',
 'GNBR::I::Gene:Gene',
 'GNBR::Q::Gene:Gene',
 'GNBR::Rg::Gene:Gene',
 'GNBR::V+::Gene:Gene',
 'GNBR::W::Gene:Gene',
 'Hetionet::GcG::Gene:Gene',
 'Hetionet::GiG::Gene:Gene',
 'Hetionet::Gr>G::Gene:Gene',
 'INTACT::ADP RIBOSYLATION REACTION::Gene:Gene',
 'INTACT::ASSOCIATION::Gene:Gene',
 'INTACT::CLEAVAGE REACTION::Gene:Gene',
 'INTACT::COLOCALIZATION::Gene:Gene',
 'INTACT::DEPHOSPHORYLATION REACTION::Gene:Gene',
 'INTACT::DIRECT INTERACTION::Gene:Gene',
 'INTACT::PHOSPHORYLATION REACTION::Gene:Gene',
 'INTACT::PHYSICAL ASSOCIATION::Gene:Gene',
 'INTACT::PROTEIN CLEAVAGE::Gene:Gene',
 'INTACT::UBIQUITINATION REACTION::Gene:Gene',
 'STRING::ACTIVATION::Gene:Gene',
 'STRING::BINDING::Gene:Gene',
 'STRING::CATALYSIS::Gene:Gene',
 'STRING::EXPRESSION::Gene:Gene',
 'STRING::INHIBITION::Gene:Gene',
 'STRING::OTHER::Gene:Gene',
 'STRING::PTMOD::Gene:Gene',
 'STRING::REACTION::Gene:Gene',
 'PrimeKG::ppi::Gene:Gene',
 'Hetionet::GpMF::Gene:MolecularFunction',
 'PrimeKG::interacts_with::Gene:MolecularFunction',
 'Hetionet::GpPW::Gene:Pathway',
 'PrimeKG::interacts_with::Gene:Pathway',
 'CTD::InPathway::Gene:Pathway',
 'PrimeKG::associated_with::Gene:Symptom',
 'GNBR::in_tax::Gene:Tax',
 'PrimeKG::interacts_with::MolecularFunction:Gene',
 'PrimeKG::parent-child::MolecularFunction:MolecularFunction',
 'PrimeKG::interacts_with::Pathway:Gene',
 'PrimeKG::parent-child::Pathway:Pathway',
 'Hetionet::PCiC::PharmacologicClass:Compound',
 'PrimeKG::side_effect::Symptom:Compound',
 'PrimeKG::phenotype_absent::Symptom:Disease',
 'PrimeKG::phenotype_present::Symptom:Disease',
 'PrimeKG::associated_with::Symptom:Gene',
 'PrimeKG::parent-child::Symptom:Symptom',
 'CTD::affects^acetylation::Compound:Gene',
 'CTD::increases^alkylation::Compound:Gene',
 'CTD::decreases^metabolic processing::Compound:Gene',
 'CTD::affects^metabolic processing::Compound:Gene',
 'CTD::decreases^acetylation::Compound:Gene',
 'CTD::decreases^amination::Compound:Gene',
 'CTD::decreases^localization::Compound:Gene',
 'CTD::increases^glucuronidation::Compound:Gene',
 'CTD::increases^sulfation::Compound:Gene',
 'CTD::affects^hydrolysis::Compound:Gene',
 'CTD::increases^hydroxylation::Compound:Gene',
 'CTD::affects^transport::Compound:Gene',
 'CTD::increases^O-linked glycosylation::Compound:Gene',
 'CTD::increases^palmitoylation::Compound:Gene',
 'CTD::increases^ADP-ribosylation::Compound:Gene',
 'CTD::increases^glutathionylation::Compound:Gene',
 'CTD::increases^glycosylation::Compound:Gene',
 'CTD::decreases^degradation::Compound:Gene',
 'CTD::decreases^cleavage::Compound:Gene',
 'CTD::affects^cleavage::Compound:Gene',
 'CTD::increases^export::Compound:Gene',
 'CTD::decreases^export::Compound:Gene',
 'CTD::affects^export::Compound:Gene',
 'CTD::decreases^sumoylation::Compound:Gene',
 'CTD::decreases^ADP-ribosylation::Compound:Gene',
 'CTD::decreases^uptake::Compound:Gene',
 'CTD::decreases^stability::Compound:Gene',
 'CTD::increases^import::Compound:Gene',
 'CTD::increases^nitrosation::Compound:Gene',
 'CTD::affects^folding::Compound:Gene',
 'CTD::affects^uptake::Compound:Gene',
 'CTD::decreases^palmitoylation::Compound:Gene',
 'CTD::increases^hydrolysis::Compound:Gene',
 'CTD::decreases^chemical synthesis::Compound:Gene',
 'CTD::decreases^ubiquitination::Compound:Gene',
 'CTD::affects^sumoylation::Compound:Gene',
 'CTD::affects^reduction::Compound:Gene',
 'CTD::affects^acylation::Compound:Gene',
 'CTD::affects^lipidation::Compound:Gene',
 'CTD::increases^prenylation::Compound:Gene',
 'CTD::affects^import::Compound:Gene',
 'CTD::decreases^farnesylation::Compound:Gene',
 'CTD::decreases^hydrolysis::Compound:Gene',
 'CTD::affects^glycosylation::Compound:Gene',
 'CTD::increases^folding::Compound:Gene',
 'CTD::decreases^ethylation::Compound:Gene',
 'CTD::decreases^reduction::Compound:Gene',
 'CTD::decreases^O-linked glycosylation::Compound:Gene',
 'CTD::decreases^folding::Compound:Gene',
 'CTD::decreases^import::Compound:Gene',
 'CTD::increases^acylation::Compound:Gene',
 'CTD::affects^degradation::Compound:Gene',
 'CTD::decreases^oxidation::Compound:Gene',
 'CTD::affects^N-linked glycosylation::Compound:Gene',
 'CTD::affects^alkylation::Compound:Gene',
 'CTD::increases^amination::Compound:Gene',
 'CTD::IS_ASSOCIATED_WITH::Disease:BiologicalProcess',
 'CTD::IS_ASSOCIATED_WITH::Disease:MolecularFunction',
 'CTD::IS_ASSOCIATED_WITH::Disease:CellularComponent',
 'CTD::IS_ASSOCIATED_WITH::Gene:Pathway',
 'CTD::IS_ASSOCIATED_WITH::Compound:Pathway',
 'CTD::IS_ASSOCIATED_WITH::Disease:Pathway',
 'CTD::IS_ASSOCIATED_WITH::Compound:Disease',
 'CTD::IS_ASSOCIATED_WITH::Gene:Disease',
 'CTD::marker/mechanism|therapeutic::Gene:Disease',
 'CTD::increases^glycation::Compound:Gene',
 'CTD::decreases^glycation::Compound:Gene',
 'CTD::increases^carbamoylation::Compound:Gene',
 'CTD::decreases^mutagenesis::Compound:Gene',
 'CTD::increases^N-linked glycosylation::Compound:Gene',
 'CTD::affects^carboxylation::Compound:Gene',
 'CTD::decreases^splicing::Compound:Gene',
 'CTD::affects^glycation::Compound:Gene',
 'CTD::affects^sulfation::Compound:Gene',
 'CTD::decreases^myristoylation::Compound:Gene',
 'CTD::decreases^prenylation::Compound:Gene',
 'CTD::affects^farnesylation::Compound:Gene',
 'CTD::decreases^geranoylation::Compound:Gene',
 'CTD::decreases^N-linked glycosylation::Compound:Gene',
 'CTD::decreases^lipidation::Compound:Gene',
 'CTD::affects^glutathionylation::Compound:Gene',
 'CTD::increases^ribosylation::Compound:Gene',
 'CTD::decreases^acylation::Compound:Gene',
 'CTD::decreases^glucuronidation::Compound:Gene',
 'CTD::affects^polymerization::Compound:Gene',
 'CTD::decreases^nitrosation::Compound:Gene',
 'CTD::decreases^carboxylation::Compound:Gene',
 'CTD::decreases^carbamoylation::Compound:Gene',
 'CTD::affects^mutagenesis::Compound:Gene',
 'CTD::decreases^alkylation::Compound:Gene',
 'CTD::decreases^glutathionylation::Compound:Gene',
 'CTD::decreases^hydroxylation::Compound:Gene',
 'CTD::decreases^sulfation::Compound:Gene',
 'CTD::affects^hydroxylation::Compound:Gene',
 'CTD::affects^glucuronidation::Compound:Gene',
 'CTD::decreases^glycosylation::Compound:Gene',
 'CTD::increases^farnesylation::Compound:Gene',
 'CTD::affects^stability::Compound:Gene',
 'CTD::affects^ubiquitination::Compound:Gene',
 'biolink::interacts_with::Gene:Gene',
 'biolink::expressed_in::Gene:Anatomy',
 'biolink::orthologous_to::Gene:Gene',
 'biolink::enables::Gene:MolecularFunction',
 'biolink::has_phenotype::Gene:Phenotype',
 'biolink::actively_involved_in::Gene:BiologicalProcess',
 'biolink::located_in::Gene:CellularComponent',
 'biolink::subclass_of::Phenotype:Phenotype',
 'biolink::has_phenotype::Disease:Phenotype',
 'biolink::acts_upstream_of_or_within::Gene:BiologicalProcess',
 'biolink::participates_in::Gene:Pathway',
 'biolink::is_active_in::Gene:CellularComponent',
 'biolink::subclass_of::Anatomy:Anatomy',
 'biolink::related_to::Phenotype:Anatomy',
 'biolink::part_of::Gene:CellularComponent',
 'biolink::participates_in::Compound:Pathway',
 'biolink::related_to::Anatomy:Anatomy',
 'biolink::subclass_of::BiologicalProcess:BiologicalProcess',
 'biolink::subclass_of::Disease:Disease',
 'biolink::subclass_of::Protein:Protein',
 'biolink::subclass_of::Compound:Compound',
 'biolink::expressed_in::Gene:CellularComponent',
 'biolink::related_to::Phenotype:BiologicalProcess',
 'biolink::related_to::Compound:Compound',
 'biolink::related_to::MolecularFunction:Compound',
 'biolink::treats_or_applied_or_studied_to_treat::Compound:Disease',
 'biolink::acts_upstream_of::Gene:BiologicalProcess',
 'biolink::related_to::BiologicalProcess:BiologicalProcess',
 'biolink::subclass_of::MolecularFunction:MolecularFunction',
 'biolink::has_mode_of_inheritance::Disease:Phenotype',
 'biolink::gene_associated_with_condition::Gene:Disease',
 'biolink::contributes_to::Gene:MolecularFunction',
 'biolink::related_to::Phenotype:CellularComponent',
 'biolink::causes::Gene:Disease',
 'biolink::subclass_of::CellularComponent:CellularComponent',
 'biolink::related_to::BiologicalProcess:Compound',
 'biolink::related_to::Phenotype:Compound',
 'biolink::colocalizes_with::Gene:CellularComponent',
 'biolink::subclass_of::Anatomy:CellularComponent',
 'biolink::related_to::CellularComponent:CellularComponent',
 'biolink::related_to::Phenotype:MolecularFunction',
 'biolink::related_to::BiologicalProcess:CellularComponent',
 'biolink::related_to::BiologicalProcess:Anatomy',
 'biolink::related_to::Disease:Disease',
 'biolink::disease_has_location::Disease:Anatomy',
 'biolink::related_to::Protein:Protein',
 'biolink::related_to::MolecularFunction:BiologicalProcess',
 'biolink::related_to::Phenotype:Phenotype',
 'biolink::related_to::Phenotype:Disease',
 'biolink::acts_upstream_of_positive_effect::Gene:BiologicalProcess',
 'biolink::related_to::Anatomy:BiologicalProcess',
 'biolink::acts_upstream_of_or_within_positive_effect::Gene:BiologicalProcess',
 'biolink::related_to::BiologicalProcess:MolecularFunction',
 'biolink::contributes_to::Gene:Disease',
 'biolink::related_to::Phenotype:Protein',
 'biolink::related_to::CellularComponent:MolecularFunction',
 'biolink::related_to::Protein:BiologicalProcess',
 'biolink::related_to::MolecularFunction:MolecularFunction',
 'biolink::related_to::CellularComponent:BiologicalProcess',
 'biolink::related_to::MolecularFunction:Protein',
 'biolink::subclass_of::Phenotype:Anatomy',
 'biolink::acts_upstream_of_negative_effect::Gene:BiologicalProcess',
 'biolink::acts_upstream_of_or_within_negative_effect::Gene:BiologicalProcess',
 'biolink::related_to::MolecularFunction:CellularComponent',
 'biolink::has_participant::Disease:BiologicalProcess',
 'biolink::has_participant::Disease:MolecularFunction',
 'biolink::disrupts::Disease:BiologicalProcess',
 'biolink::related_to::Anatomy:CellularComponent',
 'biolink::enables::Protein:MolecularFunction',
 'biolink::related_to::Disease:Compound',
 'biolink::related_to::Anatomy:Compound',
 'biolink::related_to::BiologicalProcess:Protein',
 'biolink::has_participant::Disease:CellularComponent',
 'biolink::acts_upstream_of_or_within::Protein:BiologicalProcess',
 'biolink::related_to::Protein:MolecularFunction',
 'biolink::located_in::Protein:CellularComponent',
 'biolink::related_to::CellularComponent:Compound',
 'biolink::related_to::Anatomy:Phenotype',
 'biolink::related_to::Anatomy:Protein',
 'biolink::subclass_of::Phenotype:BiologicalProcess',
 'biolink::disrupts::Disease:MolecularFunction',
 'biolink::related_to::Disease:BiologicalProcess',
 'biolink::related_to::MolecularFunction:Anatomy',
 'biolink::subclass_of::Protein:CellularComponent',
 'biolink::has_mode_of_inheritance::Gene:Phenotype',
 'biolink::related_to::Disease:Phenotype',
 'biolink::disease_has_location::Disease:CellularComponent',
 'biolink::caused_by::Disease:BiologicalProcess',
 'biolink::actively_involved_in::Protein:BiologicalProcess',
 'biolink::subclass_of::Protein:Compound',
 'biolink::related_to::CellularComponent:Protein',
 'biolink::causes::Disease:BiologicalProcess',
 'biolink::subclass_of::Phenotype:Disease',
 'biolink::part_of::Protein:CellularComponent',
 'biolink::caused_by::Disease:CellularComponent',
 'biolink::subclass_of::CellularComponent:Anatomy',
 'RepoDB::therapeutic::Compound:Disease']

In [33]:
before_count = len(df)
before_count

44793419

In [34]:
before_count = len(df)

# Filter to only keep rows that are in the relation_types list
df = df[df["relation_type"].isin(relation_types)]

after_count = len(df)
removed_count = before_count - after_count

print(f"Number of relations before filtering: {before_count}")
print(f"Number of relations after filtering: {after_count}")
print(f"Number of relations removed: {removed_count}")

Number of relations before filtering: 44793419
Number of relations after filtering: 44701374
Number of relations removed: 92045

In [35]:
df

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,DrugBank:DB00107,UMLS:C0000810,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB00107,Compound,MESH:D000027,Disease,BioMedGPS::Treatment::Compound:Disease
1,DrugBank:DB00917,UMLS:C0000810,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB00917,Compound,MESH:D000027,Disease,BioMedGPS::Treatment::Compound:Disease
2,DrugBank:DB01160,UMLS:C0000810,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB01160,Compound,MESH:D000027,Disease,BioMedGPS::Treatment::Compound:Disease
3,DrugBank:DB12789,UMLS:C0000810,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB12789,Compound,MESH:D000027,Disease,BioMedGPS::Treatment::Compound:Disease
4,DrugBank:DB03808,UMLS:C0000880,Compound,Disease,RepoDB::therapeutic::Compound:Disease,RepoDB,NaN,NaN,DrugBank:DB03808,Compound,MONDO:0005629,Disease,BioMedGPS::Treatment::Compound:Disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44793502,OMIM:613485,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0019171,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44793503,OMIM:613677,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013359,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44793504,OMIM:613980,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013513,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44793505,OMIM:614098,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0013572,Disease,BioMedGPS::AssociatedWith::Pathway:Disease
44793506,OMIM:616973,REACT:R-HSA-997272,Disease,Pathway,CTD::IS_ASSOCIATED_WITH::Disease:Pathway,CTD,NaN,NaN,REACT:R-HSA-997272,Pathway,MONDO:0014855,Disease,BioMedGPS::AssociatedWith::Pathway:Disease

In [36]:
ignore_formatted_relation_types = [
    # There are too much relations in this relation type, but they might not useful.
    "BioMedGPS::Interaction::Compound:Compound",
    # We don't like associated_with relation type.
    "BioMedGPS::AssociatedWith::Gene:Gene",
]

In [37]:
df = df[~df["formatted_relation_type"].isin(ignore_formatted_relation_types)]
print("Number of relations after removed ignore formatted_relation_types: {}".format(len(df)))

Number of relations after removed ignore formatted_relation_types: 42796799

In [38]:
df.to_csv(kg_file_ignore_relation_types_filtered, sep="\t", index=False)
kg_file = kg_file_ignore_relation_types_filtered
kg_file

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/knowledge_graph_ignore_relation_types_filtered.tsv'

### [Optional] Map all mouse genes to human genes as much as possible

#### Establish a mapping table between mice and humans

In [41]:
## Number of Mouse / Rat / Human Genes
entities = pd.read_csv(entity_file, sep="\t")
genes = entities[entities["label"] == "Gene"]
mouse_genes = genes[genes["taxid"] == 10090]
rat_genes = genes[genes["taxid"] == 10116]
human_genes = genes[genes["taxid"] == 9606]
print("Number of Entities: ", len(mouse_genes), len(rat_genes), len(human_genes))

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_87811/3387816344.py:2: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  entities = pd.read_csv(entity_file, sep="\t")

In [45]:
knowledge_graph = pd.read_csv(kg_file, sep="\t")

mouse_relations = knowledge_graph[
    knowledge_graph["source_id"].isin(mouse_genes["id"])
    | knowledge_graph["target_id"].isin(mouse_genes["id"])
]

human_relations = knowledge_graph[
    knowledge_graph["source_id"].isin(human_genes["id"])
    | knowledge_graph["target_id"].isin(human_genes["id"])
]
print(f"Number of mouse gene relations: {len(mouse_relations)}, Number of human gene relations: {len(human_relations)}")

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_87811/3875376327.py:1: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  knowledge_graph = pd.read_csv(kg_file, sep="\t")

Number of mouse gene relations: 2517961, Number of human gene relations: 31971689

In [46]:
human_mouse_gene_mappings = pd.read_csv(
    os.path.join(graph_data_dir, "mapping", "human_mouse_gene_mappings.tsv"), sep="\t"
)
# NOTE: There might be multiple mappings for a single mouse gene, we will use the first mapping for now. such as PTCD1[ENTREZ:26024] and ATP5MF-PTCD1[ENTREZ:100526740] have the same mouse gene mapping. Ptcd1[ENTREZ: 71799]. 
# human_mouse_gene_map["ENTREZ:71799"]
human_mouse_gene_map = dict(
    zip(
        human_mouse_gene_mappings["entrez_id_mouse"],
        human_mouse_gene_mappings["entrez_id_human"],
    )
)

In [47]:
human_mouse_gene_map

{'ENTREZ:23825': 'ENTREZ:8815',
 'ENTREZ:18585': 'ENTREZ:5152',
 'ENTREZ:66514': 'ENTREZ:80150',
 'ENTREZ:20480': 'ENTREZ:81570',
 'ENTREZ:13726': 'ENTREZ:2010',
 'ENTREZ:16952': 'ENTREZ:301',
 'ENTREZ:66477': 'ENTREZ:84833',
 'ENTREZ:338355': 'ENTREZ:23307',
 'ENTREZ:241116': 'ENTREZ:255101',
 'ENTREZ:665270': 'ENTREZ:151056',
 'ENTREZ:11766': 'ENTREZ:8906',
 'ENTREZ:17850': 'ENTREZ:4594',
 'ENTREZ:19386': 'ENTREZ:727851',
 'ENTREZ:620592': 'ENTREZ:27112',
 'ENTREZ:69870': 'ENTREZ:84265',
 'ENTREZ:14419': 'ENTREZ:51083',
 'ENTREZ:208043': 'ENTREZ:23067',
 'ENTREZ:21375': 'ENTREZ:10716',
 'ENTREZ:21385': 'ENTREZ:6909',
 'ENTREZ:27993': 'ENTREZ:92856',
 'ENTREZ:380718': 'ENTREZ:54903',
 'ENTREZ:56417': 'ENTREZ:103',
 'ENTREZ:217138': 'ENTREZ:79170',
 'ENTREZ:67979': 'ENTREZ:84896',
 'ENTREZ:56637': 'ENTREZ:2932',
 'ENTREZ:497652': 'ENTREZ:65057',
 'ENTREZ:71361': 'ENTREZ:84883',
 'ENTREZ:208211': 'ENTREZ:644974',
 'ENTREZ:52014': 'ENTREZ:116150',
 'ENTREZ:19892': 'ENTREZ:6121',
 'ENTREZ:12740': 'ENTREZ:1364',
 'ENTREZ:12739': 'ENTREZ:1365',
 'ENTREZ:54419': 'ENTREZ:9074',
 'ENTREZ:56863': 'ENTREZ:9080',
 'ENTREZ:56216': 'ENTREZ:112755',
 'ENTREZ:19015': 'ENTREZ:5467',
 'ENTREZ:16008': 'ENTREZ:3485',
 'ENTREZ:13389': 'ENTREZ:10683',
 'ENTREZ:13172': 'ENTREZ:120237',
 'ENTREZ:223843': 'ENTREZ:440097',
 'ENTREZ:80720': 'ENTREZ:80714',
 'ENTREZ:73316': 'ENTREZ:125972',
 'ENTREZ:22275': 'ENTREZ:7389',
 'ENTREZ:27217': 'ENTREZ:83881',
 'ENTREZ:100502766': 'ENTREZ:3833',
 'ENTREZ:16580': 'ENTREZ:3833',
 'ENTREZ:12815': 'ENTREZ:1302',
 'ENTREZ:12162': 'ENTREZ:655',
 'ENTREZ:20301': 'ENTREZ:10850',
 'ENTREZ:100040048': 'ENTREZ:10850',
 'ENTREZ:100039863': 'ENTREZ:10850',
 'ENTREZ:22771': 'ENTREZ:7545',
 'ENTREZ:19876': 'ENTREZ:6091',
 'ENTREZ:19649': 'ENTREZ:64221',
 'ENTREZ:22021': 'ENTREZ:8460',
 'ENTREZ:12227': 'ENTREZ:7832',
 'ENTREZ:15568': 'ENTREZ:1994',
 'ENTREZ:19662': 'ENTREZ:5950',
 'ENTREZ:12359': 'ENTREZ:847',
 'ENTREZ:16323': 'ENTREZ:3624',
 'ENTREZ:17536': 'ENTREZ:4212',
 'ENTREZ:20218': 'ENTREZ:10657',
 'ENTREZ:14797': 'ENTREZ:166',
 'ENTREZ:22337': 'ENTREZ:7421',
 'ENTREZ:18103': 'ENTREZ:283458',
 'ENTREZ:18102': 'ENTREZ:4830',
 'ENTREZ:79059': 'ENTREZ:4832',
 'ENTREZ:171567': 'ENTREZ:29922',
 'ENTREZ:22160': 'ENTREZ:7291',
 'ENTREZ:18538': 'ENTREZ:5111',
 'ENTREZ:140488': 'ENTREZ:10643',
 'ENTREZ:21957': 'ENTREZ:7140',
 'ENTREZ:544791': 'ENTREZ:8735',
 'ENTREZ:17884': 'ENTREZ:4622',
 'ENTREZ:17883': 'ENTREZ:4621',
 'ENTREZ:17885': 'ENTREZ:4626',
 'ENTREZ:17882': 'ENTREZ:4620',
 'ENTREZ:17879': 'ENTREZ:4619',
 'ENTREZ:17901': 'ENTREZ:4632',
 'ENTREZ:14370': 'ENTREZ:8325',
 'ENTREZ:15427': 'ENTREZ:3225',
 'ENTREZ:11465': 'ENTREZ:71',
 'ENTREZ:11461': 'ENTREZ:60',
 'ENTREZ:66775': 'ENTREZ:401494',
 'ENTREZ:15421': 'ENTREZ:3228',
 'ENTREZ:15415': 'ENTREZ:3217',
 'ENTREZ:18129': 'ENTREZ:4853',
 'ENTREZ:18131': 'ENTREZ:4854',
 'ENTREZ:11474': 'ENTREZ:89',
 'ENTREZ:258804': 'ENTREZ:81327',
 'ENTREZ:258832': 'ENTREZ:81797',
 'ENTREZ:258881': 'ENTREZ:441911',
 'ENTREZ:258784': 'ENTREZ:81327',
 'ENTREZ:259002': 'ENTREZ:402135',
 'ENTREZ:259003': 'ENTREZ:402135',
 'ENTREZ:259001': 'ENTREZ:403278',
 'ENTREZ:257948': 'ENTREZ:26529',
 'ENTREZ:257925': 'ENTREZ:26529',
 'ENTREZ:57269': 'ENTREZ:26687',
 'ENTREZ:257893': 'ENTREZ:26529',
 'ENTREZ:258267': 'ENTREZ:391107',
 'ENTREZ:57270': 'ENTREZ:26687',
 'ENTREZ:57271': 'ENTREZ:26686',
 'ENTREZ:258305': 'ENTREZ:26658',
 'ENTREZ:56407': 'ENTREZ:26133',
 'ENTREZ:12532': 'ENTREZ:995',
 'ENTREZ:12530': 'ENTREZ:993',
 'ENTREZ:12531': 'ENTREZ:994',
 'ENTREZ:53619': 'ENTREZ:10904',
 'ENTREZ:12812': 'ENTREZ:8161',
 'ENTREZ:19165': 'ENTREZ:5664',
 'ENTREZ:12005': 'ENTREZ:8312',
 'ENTREZ:12006': 'ENTREZ:8313',
 'ENTREZ:18514': 'ENTREZ:5087',
 'ENTREZ:18516': 'ENTREZ:5090',
 'ENTREZ:18515': 'ENTREZ:5089',
 'ENTREZ:13164': 'ENTREZ:1618',
 'ENTREZ:327958': 'ENTREZ:83394',
 'ENTREZ:17292': 'ENTREZ:55897',
 'ENTREZ:17293': 'ENTREZ:145873',
 'ENTREZ:12064': 'ENTREZ:627',
 'ENTREZ:14268': 'ENTREZ:2335',
 'ENTREZ:17194': 'ENTREZ:8512',
 'ENTREZ:20390': 'ENTREZ:6441',
 'ENTREZ:17195': 'ENTREZ:4153',
 'ENTREZ:228139': 'ENTREZ:5024',
 'ENTREZ:233744': 'ENTREZ:10418',
 'ENTREZ:78784': 'ENTREZ:11189',
 'ENTREZ:12166': 'ENTREZ:657',
 'ENTREZ:13190': 'ENTREZ:1638',
 'ENTREZ:17127': 'ENTREZ:4088',
 'ENTREZ:69159': 'ENTREZ:121268',
 'ENTREZ:19744': 'ENTREZ:6009',
 'ENTREZ:15111': 'ENTREZ:9464',
 'ENTREZ:66824': 'ENTREZ:29108',
 'ENTREZ:223453': 'ENTREZ:1611',
 'ENTREZ:76747': 'ENTREZ:92196',
 'ENTREZ:71609': 'ENTREZ:8717',
 'ENTREZ:12028': 'ENTREZ:581',
 'ENTREZ:30838': 'ENTREZ:6468',
 'ENTREZ:18996': 'ENTREZ:5457',
 'ENTREZ:56358': 'ENTREZ:51226',
 'ENTREZ:15214': 'ENTREZ:23493',
 'ENTREZ:13038': 'ENTREZ:1513',
 'ENTREZ:73173': 'ENTREZ:54510',
 'ENTREZ:330836': 'ENTREZ:9057',
 'ENTREZ:99633': 'ENTREZ:23266',
 'ENTREZ:54169': 'ENTREZ:23522',
 'ENTREZ:14026': 'ENTREZ:51466',
 'ENTREZ:15213': 'ENTREZ:23462',
 'ENTREZ:57741': 'ENTREZ:26155',
 'ENTREZ:15159': 'ENTREZ:3052',
 'ENTREZ:66894': 'ENTREZ:11060',
 'ENTREZ:12399': 'ENTREZ:864',
 'ENTREZ:406220': 'ENTREZ:374454',
 'ENTREZ:406222': 'ENTREZ:121391',
 'ENTREZ:432987': 'ENTREZ:286887',
 'ENTREZ:406223': 'ENTREZ:286887',
 'ENTREZ:16687': 'ENTREZ:286887',
 'ENTREZ:16688': 'ENTREZ:286887',
 'ENTREZ:110310': 'ENTREZ:3855',
 'ENTREZ:16682': 'ENTREZ:3851',
 'ENTREZ:109052': 'ENTREZ:9119',
 'ENTREZ:105866': 'ENTREZ:140807',
 'ENTREZ:16678': 'ENTREZ:3848',
 'ENTREZ:223915': 'ENTREZ:319101',
 'ENTREZ:223917': 'ENTREZ:338785',
 'ENTREZ:16691': 'ENTREZ:3856',
 'ENTREZ:77055': 'ENTREZ:51350',
 'ENTREZ:16681': 'ENTREZ:3849',
 'ENTREZ:56735': 'ENTREZ:112802',
 'ENTREZ:239673': 'ENTREZ:85340',
 'ENTREZ:12015': 'ENTREZ:572',
 'ENTREZ:27756': 'ENTREZ:57819',
 'ENTREZ:54402': 'ENTREZ:8859',
 'ENTREZ:11820': 'ENTREZ:351',
 'ENTREZ:14450': 'ENTREZ:2618',
 'ENTREZ:14106': 'ENTREZ:8928',
 'ENTREZ:15499': 'ENTREZ:3297',
 'ENTREZ:67379': 'ENTREZ:162989',
 'ENTREZ:12364': 'ENTREZ:100506742',
 'ENTREZ:12362': 'ENTREZ:834',
 'ENTREZ:12363': 'ENTREZ:838',
 'ENTREZ:11783': 'ENTREZ:317',
 'ENTREZ:17877': 'ENTREZ:4617',
 'ENTREZ:19133': 'ENTREZ:5961',
 'ENTREZ:57266': 'ENTREZ:9547',
 'ENTREZ:14465': 'ENTREZ:2627',
 'ENTREZ:21956': 'ENTREZ:7139',
 'ENTREZ:12140': 'ENTREZ:2173',
 'ENTREZ:11837': 'ENTREZ:220717',
 'ENTREZ:18049': 'ENTREZ:4803',
 'ENTREZ:22608': 'ENTREZ:4904',
 'ENTREZ:70771': 'ENTREZ:54328',
 'ENTREZ:64450': 'ENTREZ:54329',
 'ENTREZ:54369': 'ENTREZ:10201',
 'ENTREZ:22772': 'ENTREZ:7546',
 'ENTREZ:278672': 'ENTREZ:100033411',
 'ENTREZ:12370': 'ENTREZ:841',
 'ENTREZ:18628': 'ENTREZ:8863',
 'ENTREZ:14184': 'ENTREZ:2261',
 'ENTREZ:15425': 'ENTREZ:3223',
 'ENTREZ:15429': 'ENTREZ:3231',
 'ENTREZ:109663': 'ENTREZ:3227',
 'ENTREZ:15422': 'ENTREZ:3229',
 'ENTREZ:15405': 'ENTREZ:3205',
 'ENTREZ:15400': 'ENTREZ:3200',
 'ENTREZ:15401': 'ENTREZ:3201',
 'ENTREZ:15394': 'ENTREZ:3198',
 'ENTREZ:15413': 'ENTREZ:3215',
 'ENTREZ:15414': 'ENTREZ:3216',
 'ENTREZ:15396': 'ENTREZ:3207',
 'ENTREZ:15402': 'ENTREZ:3202',
 'ENTREZ:20273': 'ENTREZ:6334',
 'ENTREZ:228731': 'ENTREZ:644524',
 'ENTREZ:110532': 'ENTREZ:104',
 'ENTREZ:18563': 'ENTREZ:5091',
 'ENTREZ:434729': 'ENTREZ:53940',
 'ENTREZ:100042782': 'ENTREZ:53940',
 'ENTREZ:434726': 'ENTREZ:53940',
 'ENTREZ:434727': 'ENTREZ:53940',
 'ENTREZ:14319': 'ENTREZ:2495',
 'ENTREZ:83457': 'ENTREZ:53940',
 'ENTREZ:67634': 'ENTREZ:94033',
 'ENTREZ:71996': 'ENTREZ:53940',
 'ENTREZ:100037258': 'ENTREZ:5611',
 'ENTREZ:12520': 'ENTREZ:975',
 'ENTREZ:18715': 'ENTREZ:11040',
 'ENTREZ:16149': 'ENTREZ:972',
 'ENTREZ:20741': 'ENTREZ:6710',
 'ENTREZ:628438': 'ENTREZ:3336',
 'ENTREZ:15528': 'ENTREZ:3336',
 'ENTREZ:67087': 'ENTREZ:56998',
 'ENTREZ:14371': 'ENTREZ:8326',
 'ENTREZ:13614': 'ENTREZ:1906',
 'ENTREZ:382051': 'ENTREZ:57546',
 'ENTREZ:53404': 'ENTREZ:220202',
 'ENTREZ:14151': 'ENTREZ:2235',
 'ENTREZ:14175': 'ENTREZ:2249',
 'ENTREZ:268902': 'ENTREZ:6092',
 'ENTREZ:15373': 'ENTREZ:340784',
 'ENTREZ:18507': 'ENTREZ:5079',
 'ENTREZ:18510': 'ENTREZ:7849',
 'ENTREZ:18504': 'ENTREZ:5076',
 'ENTREZ:18508': 'ENTREZ:5080',
 'ENTREZ:18125': 'ENTREZ:4842',
 'ENTREZ:54713': 'ENTREZ:55079',
 'ENTREZ:13075': 'ENTREZ:1588',
 'ENTREZ:53624': 'ENTREZ:1366',
 'ENTREZ:22416': 'ENTREZ:89780',
 'ENTREZ:65970': 'ENTREZ:51474',
 'ENTREZ:381091': 'ENTREZ:3127',
 'ENTREZ:14961': 'ENTREZ:3120',
 'ENTREZ:15002': 'ENTREZ:3112',
 'ENTREZ:14969': 'ENTREZ:3127',
 'ENTREZ:20845': 'ENTREZ:6770',
 'ENTREZ:11933': 'ENTREZ:483',
 'ENTREZ:11932': 'ENTREZ:482',
 'ENTREZ:11931': 'ENTREZ:481',
 'ENTREZ:20682': 'ENTREZ:6662',
 'ENTREZ:18823': 'ENTREZ:5354',
 'ENTREZ:12978': 'ENTREZ:1436',
 'ENTREZ:213043': 'ENTREZ:344454',
 'ENTREZ:11761': 'ENTREZ:316',
 'ENTREZ:71724': 'ENTREZ:107126360',
 'ENTREZ:16815': 'ENTREZ:85474',
 'ENTREZ:20924': 'ENTREZ:6829',
 'ENTREZ:11864': 'ENTREZ:9915',
 'ENTREZ:13838': 'ENTREZ:2043',
 'ENTREZ:11928': 'ENTREZ:476',
 'ENTREZ:232975': 'ENTREZ:478',
 'ENTREZ:53415': 'ENTREZ:10553',
 'ENTREZ:18181': 'ENTREZ:4899',
 'ENTREZ:12677': 'ENTREZ:338917',
 'ENTREZ:13813': 'ENTREZ:8320',
 'ENTREZ:13609': 'ENTREZ:1901',
 'ENTREZ:11656': 'ENTREZ:212',
 'ENTREZ:13179': 'ENTREZ:1634',
 'ENTREZ:14979': 'ENTREZ:7923',
 'ENTREZ:21356': 'ENTREZ:6892',
 'ENTREZ:13163': 'ENTREZ:1616',
 'ENTREZ:81630': 'ENTREZ:9278',
 'ENTREZ:18390': 'ENTREZ:4988',
 'ENTREZ:18212': 'ENTREZ:4915',
 'ENTREZ:18213': 'ENTREZ:4916',
 'ENTREZ:13016': 'ENTREZ:1487',
 'ENTREZ:13017': 'ENTREZ:1488',
 'ENTREZ:19732': 'ENTREZ:5863',
 'ENTREZ:19891': 'ENTREZ:6118',
 'ENTREZ:17242': 'ENTREZ:4192',
 'ENTREZ:100040233': 'ENTREZ:154754',
 'ENTREZ:436523': 'ENTREZ:154754',
 'ENTREZ:436522': 'ENTREZ:154754',
 'ENTREZ:114228': 'ENTREZ:154754',
 'ENTREZ:22072': 'ENTREZ:5645',
 'ENTREZ:22074': 'ENTREZ:154754',
 'ENTREZ:103964': 'ENTREZ:154754',
 'ENTREZ:22073': 'ENTREZ:154754',
 'ENTREZ:13033': 'ENTREZ:1509',
 'ENTREZ:20474': 'ENTREZ:51804',
 'ENTREZ:20475': 'ENTREZ:147912',
 'ENTREZ:26419': 'ENTREZ:5599',
 'ENTREZ:26416': 'ENTREZ:1432',
 'ENTREZ:26399': 'ENTREZ:5608',
 'ENTREZ:14526': 'ENTREZ:2641',
 'ENTREZ:14573': 'ENTREZ:2668',
 'ENTREZ:14585': 'ENTREZ:2674',
 'ENTREZ:17300': 'ENTREZ:2296',
 'ENTREZ:11611': 'ENTREZ:189',
 'ENTREZ:20563': 'ENTREZ:9353',
 'ENTREZ:20564': 'ENTREZ:6586',
 'ENTREZ:258987': 'ENTREZ:119765',
 'ENTREZ:258292': 'ENTREZ:346525',
 'ENTREZ:258684': 'ENTREZ:441608',
 'ENTREZ:259018': 'ENTREZ:219453',
 'ENTREZ:259010': 'ENTREZ:8389',
 'ENTREZ:258982': 'ENTREZ:119765',
 'ENTREZ:329460': 'ENTREZ:219431',
 'ENTREZ:258946': 'ENTREZ:26740',
 'ENTREZ:258943': 'ENTREZ:138883',
 'ENTREZ:259008': 'ENTREZ:8389',
 'ENTREZ:258769': 'ENTREZ:120066',
 'ENTREZ:258693': 'ENTREZ:441608',
 'ENTREZ:259027': 'ENTREZ:8389',
 'ENTREZ:259026': 'ENTREZ:8389',
 'ENTREZ:258744': 'ENTREZ:219858',
 'ENTREZ:258902': 'ENTREZ:81309',
 'ENTREZ:258908': 'ENTREZ:390882',
 'ENTREZ:258990': 'ENTREZ:392138',
 'ENTREZ:259074': 'ENTREZ:26664',
 'ENTREZ:258883': 'ENTREZ:219858',
 'ENTREZ:258728': 'ENTREZ:120065',
 'ENTREZ:259009': 'ENTREZ:8389',
 'ENTREZ:404324': 'ENTREZ:219453',
 'ENTREZ:258833': 'ENTREZ:390148',
 'ENTREZ:258700': 'ENTREZ:390190',
 'ENTREZ:258741': 'ENTREZ:219865',
 'ENTREZ:100503486': 'ENTREZ:219865',
 'ENTREZ:404399': 'ENTREZ:219431',
 'ENTREZ:258923': 'ENTREZ:8389',
 'ENTREZ:259007': 'ENTREZ:8389',
 'ENTREZ:258991': 'ENTREZ:219958',
 'ENTREZ:259025': 'ENTREZ:8389',
 'ENTREZ:258925': 'ENTREZ:8389',
 'ENTREZ:258944': 'ENTREZ:138883',
 'ENTREZ:259011': 'ENTREZ:8389',
 'ENTREZ:258742': 'ENTREZ:219865',
 'ENTREZ:258792': 'ENTREZ:219954',
 'ENTREZ:258826': 'ENTREZ:26494',
 'ENTREZ:259044': 'ENTREZ:26659',
 'ENTREZ:258941': 'ENTREZ:138882',
 'ENTREZ:258924': 'ENTREZ:8389',
 'ENTREZ:258734': 'ENTREZ:120065',
 'ENTREZ:259024': 'ENTREZ:8389',
 'ENTREZ:258269': 'ENTREZ:283159',
 'ENTREZ:257872': 'ENTREZ:390882',
 'ENTREZ:258620': 'ENTREZ:26219',
 'ENTREZ:18310': 'ENTREZ:401427',
 'ENTREZ:258310': 'ENTREZ:26493',
 'ENTREZ:18346': 'ENTREZ:402317',
 'ENTREZ:258618': 'ENTREZ:138881',
 'ENTREZ:258314': 'ENTREZ:81127',
 'ENTREZ:193053': 'ENTREZ:8389',
 'ENTREZ:258075': 'ENTREZ:390883',
 'ENTREZ:258649': 'ENTREZ:135941',
 'ENTREZ:258249': 'ENTREZ:390882',
 'ENTREZ:227794': 'ENTREZ:254973',
 'ENTREZ:18321': 'ENTREZ:8389',
 'ENTREZ:258616': 'ENTREZ:158131',
 'ENTREZ:258280': 'ENTREZ:442179',
 'ENTREZ:258344': 'ENTREZ:8389',
 'ENTREZ:258647': 'ENTREZ:402317',
 'ENTREZ:258435': 'ENTREZ:8389',
 'ENTREZ:18328': 'ENTREZ:347168',
 'ENTREZ:258366': 'ENTREZ:402317',
 'ENTREZ:258426': 'ENTREZ:81228',
 'ENTREZ:258224': 'ENTREZ:128360',
 'ENTREZ:258046': 'ENTREZ:26494',
 'ENTREZ:258433': 'ENTREZ:283159',
 'ENTREZ:258606': 'ENTREZ:387815',
 'ENTREZ:18331': 'ENTREZ:119765',
 'ENTREZ:18322': 'ENTREZ:125963',
 'ENTREZ:257883': 'ENTREZ:126370',
 'ENTREZ:18357': 'ENTREZ:26659',
 'ENTREZ:257959': 'ENTREZ:26494',
 'ENTREZ:258656': 'ENTREZ:392390',
 'ENTREZ:258466': 'ENTREZ:403257',
 'ENTREZ:258370': 'ENTREZ:81315',
 'ENTREZ:18324': 'ENTREZ:283159',
 'ENTREZ:258328': 'ENTREZ:26494',
 'ENTREZ:258074': 'ENTREZ:390883',
 'ENTREZ:258431': 'ENTREZ:26494',
 'ENTREZ:258236': 'ENTREZ:8389',
 'ENTREZ:258313': 'ENTREZ:81127',
 'ENTREZ:258316': 'ENTREZ:81127',
 'ENTREZ:258420': 'ENTREZ:390445',
 'ENTREZ:257912': 'ENTREZ:26494',
 'ENTREZ:258097': 'ENTREZ:219956',
 'ENTREZ:18343': 'ENTREZ:26494',
 'ENTREZ:258086': 'ENTREZ:26494',
 'ENTREZ:75753': 'ENTREZ:128209',
 'ENTREZ:13544': 'ENTREZ:1857',
 'ENTREZ:225049': 'ENTREZ:57217',
 'ENTREZ:66830': 'ENTREZ:112939',
 'ENTREZ:20438': 'ENTREZ:6477',
 'ENTREZ:20437': 'ENTREZ:6477',
 'ENTREZ:93737': 'ENTREZ:84552',
 'ENTREZ:74194': 'ENTREZ:390',
 'ENTREZ:12572': 'ENTREZ:1022',
 'ENTREZ:23972': 'ENTREZ:9060',
 'ENTREZ:57255': 'ENTREZ:1364',
 'ENTREZ:12737': 'ENTREZ:9076',
 'ENTREZ:18417': 'ENTREZ:5010',
 'ENTREZ:64945': 'ENTREZ:9069',
 'ENTREZ:215114': 'ENTREZ:3092',
 'ENTREZ:22385': 'ENTREZ:9031',
 'ENTREZ:259066': 'ENTREZ:341152',
 'ENTREZ:258815': 'ENTREZ:81309',
 'ENTREZ:258899': 'ENTREZ:81309',
 'ENTREZ:258903': 'ENTREZ:81309',
 'ENTREZ:258901': 'ENTREZ:81309',
 'ENTREZ:258973': 'ENTREZ:81309',
 'ENTREZ:258894': 'ENTREZ:81309',
 'ENTREZ:257984': 'ENTREZ:81327',
 'ENTREZ:258407': 'ENTREZ:26689',
 'ENTREZ:258451': 'ENTREZ:81309',
 'ENTREZ:15114': 'ENTREZ:9001',
 'ENTREZ:57080': 'ENTREZ:9569',
 'ENTREZ:22384': 'ENTREZ:7458',
 'ENTREZ:12951': 'ENTREZ:1406',
 'ENTREZ:21869': 'ENTREZ:7080',
 'ENTREZ:69787': 'ENTREZ:312',
 'ENTREZ:17537': 'ENTREZ:257468',
 'ENTREZ:17978': 'ENTREZ:10499',
 'ENTREZ:22355': 'ENTREZ:7434',
 'ENTREZ:13361': 'ENTREZ:573971',
 'ENTREZ:14658': 'ENTREZ:2743',
 'ENTREZ:14657': 'ENTREZ:441509',
 'ENTREZ:20472': 'ENTREZ:10736',
 'ENTREZ:66256': 'ENTREZ:6746',
 'ENTREZ:68010': 'ENTREZ:25805',
 'ENTREZ:13405': 'ENTREZ:1756',
 'ENTREZ:18044': 'ENTREZ:4800',
 'ENTREZ:66923': 'ENTREZ:55193',
 'ENTREZ:53761': 'ENTREZ:7916',
 'ENTREZ:224727': 'ENTREZ:7917',
 'ENTREZ:110147': 'ENTREZ:10919',
 'ENTREZ:15361': 'ENTREZ:3159',
 'ENTREZ:111241': 'ENTREZ:3159',
 'ENTREZ:22227': 'ENTREZ:7350',
 'ENTREZ:26423': 'ENTREZ:2516',
 'ENTREZ:69454': 'ENTREZ:9022',
 'ENTREZ:241274': 'ENTREZ:375775',
 'ENTREZ:63857': 'ENTREZ:53630',
 'ENTREZ:170752': 'ENTREZ:83875',
 'ENTREZ:65960': 'ENTREZ:57045',
 'ENTREZ:244585': 'ENTREZ:23322',
 'ENTREZ:12870': 'ENTREZ:1356',
 'ENTREZ:12952': 'ENTREZ:1407',
 'ENTREZ:17528': 'ENTREZ:4359',
 'ENTREZ:11840': 'ENTREZ:375',
 'ENTREZ:14194': 'ENTREZ:2271',
 'ENTREZ:55938': 'ENTREZ:55937',
 'ENTREZ:12550': 'ENTREZ:999',
 'ENTREZ:12560': 'ENTREZ:1001',
 'ENTREZ:22196': 'ENTREZ:7329',
 'ENTREZ:16000': 'ENTREZ:3479',
 'ENTREZ:14616': 'ENTREZ:2703',
 'ENTREZ:11922': 'ENTREZ:63974',
 'ENTREZ:11925': 'ENTREZ:50674',
 'ENTREZ:110794': 'ENTREZ:1053',
 'ENTREZ:12767': 'ENTREZ:7852',
 'ENTREZ:13642': 'ENTREZ:1948',
 'ENTREZ:13641': 'ENTREZ:1947',
 'ENTREZ:13643': 'ENTREZ:1949',
 'ENTREZ:21417': 'ENTREZ:6935',
 'ENTREZ:22786': 'ENTREZ:22917',
 'ENTREZ:240672': 'ENTREZ:1847',
 'ENTREZ:16911': 'ENTREZ:8543',
 'ENTREZ:14704': 'ENTREZ:2785',
 'ENTREZ:16840': 'ENTREZ:11061',
 'ENTREZ:16371': 'ENTREZ:79192',
 'ENTREZ:54352': 'ENTREZ:10265',
 'ENTREZ:16816': 'ENTREZ:3931',
 'ENTREZ:353310': 'ENTREZ:80139',
 'ENTREZ:66352': 'ENTREZ:8548',
 'ENTREZ:13837': 'ENTREZ:2042',
 'ENTREZ:232807': 'ENTREZ:54776',
 'ENTREZ:12373': 'ENTREZ:845',
 'ENTREZ:76846': 'ENTREZ:6203',
 'ENTREZ:13423': 'ENTREZ:1777',
 'ENTREZ:13875': 'ENTREZ:2077',
 'ENTREZ:11816': 'ENTREZ:348',
 'ENTREZ:73647': 'ENTREZ:10753',
 'ENTREZ:68089': 'ENTREZ:10093',
 'ENTREZ:12226': 'ENTREZ:694',
 'ENTREZ:21933': 'ENTREZ:8793',
 'ENTREZ:24066': 'ENTREZ:81848',
 'ENTREZ:12960': 'ENTREZ:1414',
 'ENTREZ:18263': 'ENTREZ:4953',
 'ENTREZ:11600': 'ENTREZ:284',
 'ENTREZ:11601': 'ENTREZ:285',
 'ENTREZ:30924': 'ENTREZ:27329',
 'ENTREZ:17968': 'ENTREZ:4685',
 'ENTREZ:17967': 'ENTREZ:4684',
 'ENTREZ:246229': 'ENTREZ:54841',
 'ENTREZ:109065': 'ENTREZ:55172',
 'ENTREZ:18770': 'ENTREZ:5313',
 'ENTREZ:209446': 'ENTREZ:7030',
 'ENTREZ:11532': 'ENTREZ:128',
 'ENTREZ:66046': 'ENTREZ:4711',
 'ENTREZ:14390': 'ENTREZ:2551',
 'ENTREZ:19378': 'ENTREZ:8854',
 'ENTREZ:17130': 'ENTREZ:4091',
 'ENTREZ:12466': 'ENTREZ:908',
 'ENTREZ:12467': 'ENTREZ:10693',
 'ENTREZ:22235': 'ENTREZ:7358',
 'ENTREZ:13003': 'ENTREZ:1462',
 'ENTREZ:13176': 'ENTREZ:1630',
 'ENTREZ:23937': 'ENTREZ:10586',
 'ENTREZ:64242': 'ENTREZ:58157',
 'ENTREZ:18759': 'ENTREZ:5584',
 'ENTREZ:13638': 'ENTREZ:1944',
 'ENTREZ:54612': 'ENTREZ:6425',
 'ENTREZ:22628': 'ENTREZ:7532',
 'ENTREZ:14735': 'ENTREZ:2239',
 'ENTREZ:15500': 'ENTREZ:3298',
 'ENTREZ:14686': 'ENTREZ:2780',
 'ENTREZ:16598': 'ENTREZ:10365',
 'ENTREZ:16599': 'ENTREZ:51274',
 'ENTREZ:14685': 'ENTREZ:2779',
 'ENTREZ:107477': 'ENTREZ:2979',
 'ENTREZ:245650': 'ENTREZ:2986',
 'ENTREZ:14919': 'ENTREZ:3000',
 'ENTREZ:17719': 'ENTREZ:4538',
 'ENTREZ:17720': 'ENTREZ:4539',
 'ENTREZ:17721': 'ENTREZ:4540',
 'ENTREZ:17722': 'ENTREZ:4541',
 'ENTREZ:17708': 'ENTREZ:4512',
 'ENTREZ:17709': 'ENTREZ:107075310',
 'ENTREZ:17710': 'ENTREZ:4514',
 'ENTREZ:17711': 'ENTREZ:4519',
 'ENTREZ:17705': 'ENTREZ:4508',
 'ENTREZ:100503946': 'ENTREZ:4508',
 'ENTREZ:17716': 'ENTREZ:4535',
 'ENTREZ:17717': 'ENTREZ:4536',
 'ENTREZ:17718': 'ENTREZ:4537',
 'ENTREZ:12367': 'ENTREZ:836',
 'ENTREZ:22433': 'ENTREZ:7494',
 'ENTREZ:56473': 'ENTREZ:9415',
 'ENTREZ:60527': 'ENTREZ:3995',
 'ENTREZ:59021': 'ENTREZ:5862',
 'ENTREZ:22352': 'ENTREZ:7431',
 'ENTREZ:108147': 'ENTREZ:471',
 'ENTREZ:75456': 'ENTREZ:221823',
 'ENTREZ:19139': 'ENTREZ:5631',
 'ENTREZ:21418': 'ENTREZ:7020',
 'ENTREZ:13077': 'ENTREZ:1544',
 'ENTREZ:13076': 'ENTREZ:1543',
 'ENTREZ:16449': 'ENTREZ:182',
 'ENTREZ:16450': 'ENTREZ:3714',
 'ENTREZ:18626': 'ENTREZ:5187',
 'ENTREZ:18627': 'ENTREZ:8864',
 'ENTREZ:244551': 'ENTREZ:342977',
 'ENTREZ:12709': 'ENTREZ:1152',
 'ENTREZ:21410': 'ENTREZ:6928',
 'ENTREZ:19156': 'ENTREZ:5660',
 'ENTREZ:76943': 'ENTREZ:768239',
 'ENTREZ:20190': 'ENTREZ:6261',
 'ENTREZ:80907': 'ENTREZ:114294',
 'ENTREZ:12606': 'ENTREZ:1050',
 'ENTREZ:12608': 'ENTREZ:1051',
 'ENTREZ:12609': 'ENTREZ:1052',
 'ENTREZ:12611': 'ENTREZ:1054',
 'ENTREZ:14083': 'ENTREZ:5747',
 'ENTREZ:140477': 'ENTREZ:127343',
 'ENTREZ:231044': 'ENTREZ:2636',
 'ENTREZ:17268': 'ENTREZ:4211',
 'ENTREZ:18771': 'ENTREZ:5316',
 'ENTREZ:14739': 'ENTREZ:9294',
 'ENTREZ:14799': 'ENTREZ:2890',
 'ENTREZ:14800': 'ENTREZ:2891',
 'ENTREZ:53623': 'ENTREZ:2892',
 'ENTREZ:14802': 'ENTREZ:2893',
 'ENTREZ:12288': 'ENTREZ:775',
 'ENTREZ:63958': 'ENTREZ:10277',
 'ENTREZ:21909': 'ENTREZ:3196',
 'ENTREZ:54484': 'ENTREZ:23608',
 'ENTREZ:22652': 'ENTREZ:7681',
 'ENTREZ:67027': 'ENTREZ:23609',
 'ENTREZ:100042614': 'ENTREZ:28670',
 'ENTREZ:667583': 'ENTREZ:28670',
 'ENTREZ:21507': 'ENTREZ:28670',
 'ENTREZ:19268': 'ENTREZ:5792',
 'ENTREZ:19280': 'ENTREZ:5802',
 'ENTREZ:58198': 'ENTREZ:6299',
 'ENTREZ:20689': 'ENTREZ:27164',
 'ENTREZ:54383': 'ENTREZ:1912',
 'ENTREZ:14077': 'ENTREZ:2170',
 'ENTREZ:14080': 'ENTREZ:2168',
 'ENTREZ:12903': 'ENTREZ:1381',
 'ENTREZ:19660': 'ENTREZ:5948',
 'ENTREZ:12904': 'ENTREZ:1382',
 'ENTREZ:171463': 'ENTREZ:54756',
 'ENTREZ:12450': 'ENTREZ:900',
 'ENTREZ:110304': 'ENTREZ:8001',
 'ENTREZ:93837': 'ENTREZ:117154',
 'ENTREZ:13134': 'ENTREZ:1602',

#### Convert mouse genes to human genes

In [49]:
# We don't like mouse genes, let's convert them to human genes. If a mouse gene doesn't have a human gene mapping, we will keep the mouse gene. So the users can see that the gene is a mouse gene.
# Convert the mouse_genes["id"] Series to a set for faster lookup
mouse_gene_ids = set(mouse_genes["id"].values)

# Vectorized operation for source_id
knowledge_graph["source_id"] = knowledge_graph["source_id"].map(
    lambda x: human_mouse_gene_map.get(x, x) if x in mouse_gene_ids else x
)

# Vectorized operation for target_id
knowledge_graph["target_id"] = knowledge_graph["target_id"].map(
    lambda x: human_mouse_gene_map.get(x, x) if x in mouse_gene_ids else x
)

# Check whether the conversion is successful
# Extract all relations (`converted_mouse_relations`) that still contain a mouse gene ID after conversion. 
converted_mouse_relations = knowledge_graph[
    knowledge_graph["source_id"].isin(mouse_genes["id"])
    | knowledge_graph["target_id"].isin(mouse_genes["id"])
]
#Extract all relations (`converted_human_relations`) where either side is a human gene ID.
converted_human_relations = knowledge_graph[
    knowledge_graph["source_id"].isin(human_genes["id"])
    | knowledge_graph["target_id"].isin(human_genes["id"])
]

# We cannot use the pattern below because some gene names don't follow the pattern. for example, "Bdnf" is used as a human gene in GNBR database.
# pattern = r"^[A-Z][a-z]+$"
# not_matched_genes = knowledge_graph[
#     ((knowledge_graph["source_type"] == "Gene") & knowledge_graph["source_name"].str.match(pattern, na=False)) |
#     ((knowledge_graph["target_type"] == "Gene") & knowledge_graph["target_name"].str.match(pattern, na=False))
# ]
# not_matched_genes[
#     (not_matched_genes["source_id"] == "ENTREZ:627")
#     | (not_matched_genes["target_id"] == "ENTREZ:627")
# ]
#The variable `converted_not_matched_genes` contains all relations that do not include mouse IDs.
converted_not_matched_genes = knowledge_graph[
    ~(
        knowledge_graph["source_id"].isin(mouse_genes["id"])
        | knowledge_graph["target_id"].isin(mouse_genes["id"])
    )
]

# Expected: 0, xxx
print(
    "Mouse: ",
    len(mouse_relations),
    " Before /",
    len(converted_mouse_relations),
    " After /",
    len(converted_not_matched_genes),
    " Not matched",
)
print(
    "Human: ",
    len(human_relations),
    " Before /",
    len(converted_human_relations),
    " After",
)

Mouse:  2517961  Before / 656566  After / 42140233  Not matched
Human:  31971689  Before / 33788476  After

In [50]:
# Write the knowledge graph to a file
kg_file_mouse_converted = os.path.join(temp_dir, "knowledge_graph_mouse_converted.tsv")
knowledge_graph.to_csv(kg_file_mouse_converted, sep="\t", index=False)

dataset_metadata.add_step(
    note="Map all mouse genes to human genes as much as possible",
    entity_file_before=entity_file,
    entity_file_after=entity_file,
    relation_file_before=kg_file,
    relation_file_after=kg_file_mouse_converted,
)

kg_file = kg_file_mouse_converted

In [75]:
kg_file

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpyrhh8j0k/knowledge_graph_mouse_converted.tsv'

### [Optional] Format all relation types

#### Check whether there are any omissions in the mapping

In [51]:
if relation_type_file and os.path.exists(relation_type_file):
    relation_types = pd.read_csv(relation_type_file, sep="\t")

    print("Number of relation types: {}".format(len(relation_types)))

Number of relation types: 402

In [52]:
 # Read the kg file
knowledge_graph = pd.read_csv(kg_file, sep="\t")

/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/ipykernel_87811/3092633169.py:2: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  knowledge_graph = pd.read_csv(kg_file, sep="\t")

In [53]:
knowledge_graph_origin = knowledge_graph

In [62]:
no_biogpsmed_relations = knowledge_graph_origin[
    ~(
        knowledge_graph_origin["formatted_relation_type"].str.startswith("BioMedGPS:", na=False)
    )
]

biogpsmed_relations = knowledge_graph_origin[
        knowledge_graph_origin["formatted_relation_type"].str.startswith("BioMedGPS:", na=False)
]
# Print the number of entries and the type of relationship
print("Number of relations with relation_type not starting with 'BioMedGPS:':", len(no_biogpsmed_relations))
print(no_biogpsmed_relations["formatted_relation_type"].unique())

print("Number of relations with relation_type not starting with 'BioMedGPS:':", len(biogpsmed_relations))
print(biogpsmed_relations["formatted_relation_type"].unique())

Number of relations with relation_type not starting with 'BioMedGPS:': 14027
['DRUGBANK::treats::Compound:Disease' 'Hetionet::GpPW::Gene:Pathway']
Number of relations with relation_type not starting with 'BioMedGPS:': 42782772
['BioMedGPS::Treatment::Compound:Disease' 'BioMedGPS::E-::Disease:Gene'
 'BioMedGPS::E+::Disease:Gene' 'BioMedGPS::Agonist::Compound:Gene'
 'BioMedGPS::Modulator::Compound:Gene'
 'BioMedGPS::Inhibitor::Compound:Gene'
 'BioMedGPS::AllostericModulator::Compound:Gene'
 'BioMedGPS::Blocker::Compound:Gene' 'BioMedGPS::Binder::Compound:Gene'
 'BioMedGPS::Antibody::Compound:Gene'
 'BioMedGPS::Activator::Compound:Gene' 'BioMedGPS::E+::Compound:Gene'
 'BioMedGPS::AssociatedWith::Compound:Gene'
 'BioMedGPS::Antagonist::Compound:Gene'
 'BioMedGPS::SimilarWith::Disease:Disease'
 'BioMedGPS::SimilarWith::Compound:Compound'
 'BioMedGPS::InPC::Compound:PharmacologicClass'
 'BioMedGPS::Interaction::Gene:Gene' 'BioMedGPS::Influencer::Gene:Gene'
 'BioMedGPS::Binder::Gene:Gene' 'BioMedGPS::AssociatedWith::Gene:Disease'
 'BioMedGPS::E::Anatomy:Gene' 'BioMedGPS::E-::Anatomy:Gene'
 'BioMedGPS::E+::Anatomy:Gene' 'BioMedGPS::E::Compound:Gene'
 'BioMedGPS::PharmacoKinetics::Compound:Gene'
 'BioMedGPS::Activator::Gene:Gene' 'BioMedGPS::E::Gene:Gene'
 'BioMedGPS::E-::Compound:Gene' 'BioMedGPS::Covary::Gene:Gene'
 'BioMedGPS::InPathway::Gene:Gene'
 'BioMedGPS::PhosphorylationReaction::Gene:Gene'
 'BioMedGPS::DePhosphorylationReaction::Gene:Gene'
 'BioMedGPS::Inhibitor::Gene:Gene' 'BioMedGPS::E+::Gene:Gene'
 'BioMedGPS::PostTranslationalMod::Gene:Gene'
 'BioMedGPS::InComplex::Gene:Gene' 'BioMedGPS::Carrier::Gene:Compound'
 'BioMedGPS::InLocation::Gene:Gene'
 'BioMedGPS::Interaction::Compound:Gene'
 'BioMedGPS::AdpRibosylationReaction::Gene:Gene'
 'BioMedGPS::UbiquitinationReaction::Gene:Gene'
 'BioMedGPS::CleavageReaction::Gene:Gene'
 'BioMedGPS::ProteinCleavage::Gene:Gene'
 'BioMedGPS::InBP::Gene:BiologicalProcess'
 'BioMedGPS::InMF::Gene:MolecularFunction'
 'BioMedGPS::InCC::Gene:CellularComponent'
 'BioMedGPS::Causer::Gene:Disease'
 'BioMedGPS::SideEffect::Compound:Disease'
 'BioMedGPS::Causer::Compound:Disease' 'BioMedGPS::Target::Gene:Disease'
 'BioMedGPS::Promotor::Gene:Disease' 'BioMedGPS::Risky::Gene:Disease'
 'BioMedGPS::Biomarker::Compound:Disease'
 'BioMedGPS::Biomarker::Gene:Disease'
 'BioMedGPS::LocatedIn::Disease:Anatomy'
 'BioMedGPS::InPathway::Gene:Pathway' 'BioMedGPS::Target::Gene:Compound'
 'BioMedGPS::AssociatedWith::Compound:Disease'
 'BioMedGPS::AssociatedWith::BiologicalProcess:Compound'
 'BioMedGPS::Participation::Compound:Pathway'
 'BioMedGPS::Interaction::Gene:Pathway'
 'BioMedGPS::Interaction::Gene:BiologicalProcess'
 'BioMedGPS::AssociatedWith::Disease:BiologicalProcess'
 'BioMedGPS::AssociatedWith::Disease:MolecularFunction'
 'BioMedGPS::AssociatedWith::Disease:CellularComponent'
 'BioMedGPS::AssociatedWith::CellularComponent:Compound'
 'BioMedGPS::AssociatedWith::BiologicalProcess:BiologicalProcess'
 'BioMedGPS::Causer::BiologicalProcess:Disease'
 'BioMedGPS::Interaction::Gene:CellularComponent'
 'BioMedGPS::AssociatedWith::Gene:Pathway'
 'BioMedGPS::AssociatedWith::Pathway:Disease'
 'BioMedGPS::Contraindication::Compound:Disease'
 'BioMedGPS::AssociatedWith::Compound:Pathway'
 'BioMedGPS::AssociatedWith::Compound:Compound'
 'BioMedGPS::AssociatedWith::Anatomy:Compound'
 'BioMedGPS::AssociatedWith::Disease:Disease'
 'BioMedGPS::Disrupt::Disease:BiologicalProcess'
 'BioMedGPS::Causer::CellularComponent:Disease'
 'BioMedGPS::AssociatedWith::MolecularFunction:Compound'
 'BioMedGPS::ParentChild::Compound:Compound'
 'BioMedGPS::AssociatedWith::Phenotype:Compound'
 'BioMedGPS::Participation::Gene:BiologicalProcess'
 'BioMedGPS::Participation::BiologicalProcess:Disease'
 'BioMedGPS::AssociatedWith::CellularComponent:MolecularFunction'
 'BioMedGPS::ParentChild::MolecularFunction:MolecularFunction'
 'BioMedGPS::Interaction::Gene:MolecularFunction'
 'BioMedGPS::ParentChild::BiologicalProcess:BiologicalProcess'
 'BioMedGPS::AssociatedWith::MolecularFunction:MolecularFunction'
 'BioMedGPS::AssociatedWith::Phenotype:MolecularFunction'
 'BioMedGPS::AssociatedWith::BiologicalProcess:MolecularFunction'
 'BioMedGPS::AssociatedWith::BiologicalProcess:CellularComponent'
 'BioMedGPS::ParentChild::CellularComponent:CellularComponent'
 'BioMedGPS::AssociatedWith::CellularComponent:CellularComponent'
 'BioMedGPS::LocatedIn::Gene:CellularComponent'
 'BioMedGPS::Participation::MolecularFunction:Disease'
 'BioMedGPS::LocatedIn::Disease:CellularComponent'
 'BioMedGPS::AssociatedWith::Phenotype:BiologicalProcess'
 'BioMedGPS::AssociatedWith::Anatomy:BiologicalProcess'
 'BioMedGPS::AssociatedWith::Anatomy:CellularComponent'
 'BioMedGPS::AssociatedWith::Phenotype:CellularComponent'
 'BioMedGPS::Disrupt::Disease:MolecularFunction'
 'BioMedGPS::Participation::CellularComponent:Disease'
 'BioMedGPS::ParentChild::Anatomy:CellularComponent'
 'BioMedGPS::Promotor::Disease:BiologicalProcess'
 'BioMedGPS::Present::Gene:Phenotype'
 'BioMedGPS::ParentChild::Phenotype:Phenotype'
 'BioMedGPS::Present::Disease:Phenotype'
 'BioMedGPS::InheritancePattern::Gene:Phenotype'
 'BioMedGPS::InheritancePattern::Disease:Phenotype'
 'BioMedGPS::AssociatedWith::Phenotype:Phenotype'
 'BioMedGPS::Orthologs::Gene:Gene'
 'BioMedGPS::ParentChild::Disease:Disease'
 'BioMedGPS::ParentChild::Anatomy:Anatomy'
 'BioMedGPS::AssociatedWith::BiologicalProcess:Anatomy'
 'BioMedGPS::AssociatedWith::Phenotype:Anatomy'
 'BioMedGPS::AssociatedWith::Anatomy:Anatomy'
 'BioMedGPS::AssociatedWith::Anatomy:MolecularFunction'
 'BioMedGPS::ParentChild::CellularComponent:Anatomy']

In [61]:
 # Format the relation types
    ## Remove the formatted_relation_type column if it exists
if "formatted_relation_type" in no_biogpsmed_relations.columns:
    no_biogpsmed_relations = no_biogpsmed_relations.drop(columns=["formatted_relation_type"])
    no_biogpsmed_relations = no_biogpsmed_relations.merge(relation_types[["relation_type", "formatted_relation_type"]], on="relation_type", how="left")
no_biogpsmed_relations

,raw_source_id,raw_target_id,raw_source_type,raw_target_type,relation_type,resource,pmids,key_sentence,source_id,source_type,target_id,target_type,formatted_relation_type
0,SYMBOL:CCR2,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:729230,Gene,MONDO:0957421,Disease,BioMedGPS::Treatment::Compound:Disease
1,SYMBOL:F9,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:2158,Gene,MONDO:0957421,Disease,BioMedGPS::Treatment::Compound:Disease
2,SYMBOL:HPD,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:3242,Gene,MONDO:0957421,Disease,BioMedGPS::Treatment::Compound:Disease
3,SYMBOL:KRT6A,ICD-11:1C80,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:3853,Gene,MONDO:0957421,Disease,BioMedGPS::Treatment::Compound:Disease
4,SYMBOL:APOH,ICD-11:4A45,Gene,Disease,DRUGBANK::treats::Compound:Disease,TTD,NaN,NaN,ENTREZ:350,Gene,MONDO:0007140,Disease,BioMedGPS::Treatment::Compound:Disease
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14022,SYMBOL:PTGFR,WikiPathways:WP98,Gene,Pathway,Hetionet::GpPW::Gene:Pathway,TTD,NaN,NaN,ENTREZ:5737,Gene,WikiPathways:WP98,Pathway,BioMedGPS::InPathway::Gene:Pathway
14023,SYMBOL:PTGIR,WikiPathways:WP98,Gene,Pathway,Hetionet::GpPW::Gene:Pathway,TTD,NaN,NaN,ENTREZ:5739,Gene,WikiPathways:WP98,Pathway,BioMedGPS::InPathway::Gene:Pathway
14024,SYMBOL:PTGS1,WikiPathways:WP98,Gene,Pathway,Hetionet::GpPW::Gene:Pathway,TTD,NaN,NaN,ENTREZ:5742,Gene,WikiPathways:WP98,Pathway,BioMedGPS::InPathway::Gene:Pathway
14025,SYMBOL:PTGS2,WikiPathways:WP98,Gene,Pathway,Hetionet::GpPW::Gene:Pathway,TTD,NaN,NaN,ENTREZ:5743,Gene,WikiPathways:WP98,Pathway,BioMedGPS::InPathway::Gene:Pathway
14026,SYMBOL:TBXAS1,WikiPathways:WP98,Gene,Pathway,Hetionet::GpPW::Gene:Pathway,TTD,NaN,NaN,ENTREZ:6916,Gene,WikiPathways:WP98,Pathway,BioMedGPS::InPathway::Gene:Pathway

In [63]:
knowledge_graph_formatted_relation_type = pd.concat([biogpsmed_relations, no_biogpsmed_relations], ignore_index=True)
print("Number of combind knowledge graph: {}".format(len(knowledge_graph_formatted_relation_type)))

Number of combind knowledge graph: 42796799

#### Check whether there are any omissions in the mapping

In [65]:
###Check whether there are any omissions in the mapping
invalid_knowledge_graph = knowledge_graph_formatted_relation_type[knowledge_graph_formatted_relation_type["formatted_relation_type"].isna()]
print("Number of invalid knowledge graph: {}".format(len(invalid_knowledge_graph)))

invalid_knowledge_graph_file = os.path.join(temp_dir, "invalid_knowledge_graph.tsv")
invalid_knowledge_graph.to_csv(invalid_knowledge_graph_file, sep="\t", index=False)
print("Please check the invalid knowledge graph file: {}".format(invalid_knowledge_graph_file))

Number of invalid knowledge graph: 0
Please check the invalid knowledge graph file: /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/invalid_knowledge_graph.tsv

In [66]:
kg_file_relation_types_formatted = os.path.join(temp_dir, "knowledge_graph_relation_types_formatted.tsv")
knowledge_graph_formatted_relation_type.to_csv(kg_file_relation_types_formatted, sep="\t", index=False)

dataset_metadata.add_step(
    note="Format the relation types",
    entity_file_before=entity_file,
    entity_file_after=entity_file,
    relation_file_before=kg_file,
    relation_file_after=kg_file_relation_types_formatted,
)
    
kg_file = kg_file_relation_types_formatted

In [67]:
kg_file

'/var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/knowledge_graph_relation_types_formatted.tsv'

### Annotate the knowledge graph with the entities

In [68]:
args = [
    "python3",
    os.path.join(os.path.dirname(lib_dir), "graph_data", "scripts", "annotate_relations.py"),
    "--entity-file",
    entity_file,
    "--relation-file",
    kg_file,
    "--output-dir",
    os.path.dirname(kg_file),
    "--strict-mode" if skip_rows_not_in_entity_file else "",
]

print("Running: {}".format(" ".join(args)))
args_str = " ".join(args)
!{args_str}
annotated_kg_file = os.path.join(temp_dir, "annotated_knowledge_graph.tsv")
print("File written to: {}".format(annotated_kg_file))

dataset_metadata.add_step(
    note="Annotate the knowledge graph with the entities",
    entity_file_before=entity_file,
    entity_file_after=entity_file,
    relation_file_before=kg_file,
    relation_file_after=annotated_kg_file,
)

Running: python3 /Users/zhuzhixing/KG/biomedgps-data/graph_data/scripts/annotate_relations.py --entity-file /Users/zhuzhixing/KG/biomedgps-data/graph_data/entities.tsv --relation-file /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/knowledge_graph_relation_types_formatted.tsv --output-dir /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt --strict-mode
Found 42796799 relations in the input file
You're in strict mode, so 0 relations were skipped.
File written to: /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/annotated_knowledge_graph.tsv

### Extract valid entities from the knowledge graph

In [69]:
import pandas as pd

knowledge_graph = pd.read_csv(kg_file, sep="\t", low_memory=False)
entities = pd.read_csv(entity_file, sep="\t", low_memory=False)

source_entities = knowledge_graph[["source_id", "source_type"]].drop_duplicates()
source_entities.columns = ["id", "label"]
target_entities = knowledge_graph[["target_id", "target_type"]].drop_duplicates()
target_entities.columns = ["id", "label"]
source_target_entities = pd.concat([source_entities, target_entities]).drop_duplicates()

valid_entities = pd.merge(source_target_entities, entities, on=["id", "label"], how="left", indicator=True)
knowledge_graph_entities_file = os.path.join(temp_dir, "knowledge_graph_entities.tsv")
valid_entities.to_csv(knowledge_graph_entities_file, sep="\t", index=False)

### Copy all files to the dataset folder

In [70]:
os.makedirs(outputdir, exist_ok=True)

files = [
    (entity_file, os.path.join(outputdir, "annotated_entities.tsv")),
    (kg_file, os.path.join(outputdir, "knowledge_graph.tsv")),
    (annotated_kg_file, os.path.join(outputdir, "annotated_knowledge_graph.tsv")),
    (knowledge_graph_entities_file, os.path.join(outputdir, "knowledge_graph_entities.tsv")),
]

In [71]:
for f, output_file in files:
    print("Copying {} to {}".format(f, output_file))
    subprocess.check_output(["cp", f, output_file])
    output_zip_file = output_file + ".zip"
    print("Zipping {} to {}".format(output_file, output_zip_file))
    subprocess.check_output(["zip", "-j", output_zip_file, output_file])
    print("Removing {}".format(output_file))
    subprocess.check_output(["rm", output_file])

print("Please found all files in {}".format(outputdir))

Copying /Users/zhuzhixing/KG/biomedgps-data/graph_data/entities.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/annotated_entities.tsv
Zipping /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/annotated_entities.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/annotated_entities.tsv.zip
Removing /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/annotated_entities.tsv
Copying /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/knowledge_graph_relation_types_formatted.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/knowledge_graph.tsv
Zipping /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/knowledge_graph.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/knowledge_graph.tsv.zip
Removing /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/knowledge_graph.tsv
Copying /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/annotated_knowledge_graph.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/annotated_knowledge_graph.tsv
Zipping /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/annotated_knowledge_graph.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/annotated_knowledge_graph.tsv.zip
Removing /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/annotated_knowledge_graph.tsv
Copying /var/folders/fp/m7jlbzzj4wldhdvbmlxw2h140000gn/T/tmpj6_2hxgt/knowledge_graph_entities.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/knowledge_graph_entities.tsv
Zipping /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/knowledge_graph_entities.tsv to /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/knowledge_graph_entities.tsv.zip
Removing /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec/knowledge_graph_entities.tsv
Please found all files in /Users/zhuzhixing/KG/biomedgps-data/datasets/biomedgps-v20250928-df0cec

### Upload the dataset to Dropbox and Dataverse

You can upload the dataset to Dropbox first, then select the files from Dropbox to upload to Dataverse.

https://dataverse.harvard.edu/dataverse/biomedgps